/* Lightweight editable scene: DOM layers share their image assets and allocate no PSD caches. */
window.CaptureDesign=(()=>{
 const frame=()=>new Promise(r=>requestAnimationFrame(r));
 const rgba=c=>`rgba(${Math.round((c?.r||0)*255)},${Math.round((c?.g||0)*255)},${Math.round((c?.b||0)*255)},${c?.a??1})`;
 const hex=c=>'#'+[c?.r||0,c?.g||0,c?.b||0].map(v=>Math.max(0,Math.min(255,Math.round(v*255))).toString(16).padStart(2,'0')).join('');
 const color=s=>({r:parseInt(s.slice(1,3),16)/255,g:parseInt(s.slice(3,5),16)/255,b:parseInt(s.slice(5,7),16)/255,a:1});
 function clone(data){function n(v){return {...v,background:v.background&&{...v.background},color:v.color&&{...v.color},rasterStyle:v.rasterStyle&&{...v.rasterStyle},radii:v.radii&&[...v.radii],borders:v.borders?.map(b=>({...b,color:b.color&&{...b.color}})),runs:v.runs?.map(r=>({...r})),children:v.children?.map(n)}}return {...data,root:n(data.root)}}
 function index(data){const map=new Map(),seen=new Set();let seq=0;function visit(n,parent,depth){if(!n._sid||!/^[\w-]{1,80}$/.test(n._sid)||seen.has(n._sid))n._sid='layer-'+(++seq);while(seen.has(n._sid))n._sid='layer-'+(++seq);seen.add(n._sid);map.set(n._sid,{node:n,parent,depth});(n.children||[]).forEach(c=>visit(c,n,depth+1))}visit(data.root,null,0);return map}
 function bounds(n){if(n.type!=='group')return {x:n.x,y:n.y,width:n.width,height:n.height};const bs=(n.children||[]).map(bounds);if(!bs.length)return {x:0,y:0,width:1,height:1};const x=Math.min(...bs.map(b=>b.x)),y=Math.min(...bs.map(b=>b.y));return {x,y,width:Math.max(1,Math.max(...bs.map(b=>b.x+b.width))-x),height:Math.max(1,Math.max(...bs.map(b=>b.y+b.height))-y)}}
 function move(n,dx,dy,children=true){if(n.type!=='group'){n.x+=dx;n.y+=dy}if(n.runs)n.runs.forEach(r=>{r.x+=dx;r.y+=dy});if(children)(n.children||[]).forEach(c=>move(c,dx,dy))}
 function svg(source){const doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror'))return null;doc.querySelectorAll('script,foreignObject,style,animate,animateTransform,set').forEach(n=>n.remove());for(const el of doc.querySelectorAll('*'))for(const a of [...el.attributes])if(a.name==='style'||/^on/i.test(a.name)||((a.localName==='href'||a.name==='src')&&!a.value.startsWith('#'))||/url\(\s*['"]?(?!#)/i.test(a.value))el.removeAttribute(a.name);const root=doc.documentElement;if(root.tagName.toLowerCase()!=='svg')return null;root.style.cssText='display:block;width:100%;height:100%;pointer-events:none';return document.importNode(root,true)}
 function painted(n){
  if(n.type==='text')return !!String(n.text||'').trim();
  if(n.type==='image')return !!(n.image||n.imageSource);
  if(n.type==='svg')return /<(?:path|rect|circle|ellipse|line|polyline|polygon|text|image|use)\b/i.test(n.svg||'');
  return n.background?.a>0||(n.borders||[]).some(b=>b.width>0&&b.style!=='none'&&b.color?.a>0)||['background-image','box-shadow'].some(k=>n.rasterStyle?.[k]&&n.rasterStyle[k]!=='none');
 }
 function clean(data){
  let removed=0,flattened=0;
  function visit(n,root=false){n.children=(n.children||[]).flatMap(c=>visit(c));const visual=painted(n);
   if(!root&&!visual&&!n.children.length){removed++;return []}
   // Coordinates are absolute. Only flatten layout wrappers with no clipping or compositing effect.
   if(!root&&!visual&&['box','group'].includes(n.type)&&!n.clip&&!n.locked&&n.visible!==false&&(n.opacity??1)===1&&!n._studioGroup){flattened++;return n.children}
   return [n];
  }
  visit(data.root,true);return {removed,flattened};
 }
 const cssKeys=['background-image','background-size','background-position','background-repeat','box-shadow'];
 function style(el,n,origin){const b=bounds(n);el.style.cssText='position:absolute;box-sizing:border-box;';Object.assign(el.style,{left:(b.x-origin.x)+'px',top:(b.y-origin.y)+'px',width:b.width+'px',height:b.height+'px',opacity:String(n.opacity??1),display:n.visible===false?'none':'block'});el.dataset.node=n._sid;el.className='design-node '+n.type;el.style.pointerEvents=painted(n)?'auto':'none';el.style.overflow=n.clip?'hidden':'visible';el.style.borderRadius=(n.radii||[0,0,0,0]).map(v=>v+'px').join(' ');if(n.background)el.style.backgroundColor=rgba(n.background);for(const k of cssKeys){const value=n.rasterStyle?.[k];if(value&&!/url\(|image-set\(|@import/i.test(value))el.style.setProperty(k,value)}(n.borders||[]).forEach((v,i)=>{if(v.width>0&&v.style!=='none')el.style['border'+['Top','Right','Bottom','Left'][i]]=v.width+'px '+v.style+' '+rgba(v.color)});return b}
 function content(el,n){if(n.type==='text'){ShijieText.apply(el,n);el.style.color=rgba(n.color);if(n.runs?.length){for(const run of n.runs){const span=document.createElement('span');span.textContent=run.text;span.style.cssText='position:absolute;white-space:pre;left:'+(run.x-n.x)+'px;top:'+(run.y-n.y)+'px;line-height:'+(run.height||n.lineHeight||n.fontSize*1.2)+'px';el.append(span)}}else el.textContent=n.text||''}
 else if(n.type==='image'){const image=document.createElement('img');image.alt='';image.draggable=false;image.loading='lazy';image.decoding='async';image.style.cssText='width:100%;height:100%;display:block;pointer-events:none;';image.style.objectFit=n.objectFit||(n.fit==='FIT'?'contain':n.fit==='STRETCH'?'fill':'cover');image.style.objectPosition=n.objectPosition||'50% 50%';image.style.borderRadius='inherit';if(n.maskImage&&!/url\(/i.test(n.maskImage))image.style.maskImage=n.maskImage;if(n.image)image.src=n.image;else{el.classList.add('missing-image');el.title='原页面图片未能嵌入'}el.append(image)}
 else if(n.type==='svg'){const s=svg(n.svg||'');if(s)el.append(s)}}
 async function render(data,board,onProgress=()=>{},signal){const total=index(data).size,elements=new Map();let done=0;board.replaceChildren();board.style.width=data.width+'px';board.style.height=data.height+'px';board.style.background=data.background?rgba(data.background):'transparent';async function visit(n,host,origin){if(signal?.aborted)throw new DOMException('已取消','AbortError');const el=document.createElement('div'),b=style(el,n,data._linkChildren===false?{x:0,y:0}:origin);el.dataset.independent=String(data._linkChildren===false);content(el,n);elements.set(n._sid,el);(data._linkChildren===false?board:host).append(el);done++;if(done%100===0){onProgress(done/total);await frame()}for(const child of n.children||[])await visit(child,el,{x:b.x+(n.borders?.[3]?.width||0),y:b.y+(n.borders?.[0]?.width||0)})}await visit(data.root,board,{x:0,y:0});onProgress(1);return elements}
 function update(n,elements,parent){const el=elements.get(n._sid);if(!el)return;const childEls=[...el.children].filter(c=>c.classList.contains('design-node'));el.replaceChildren();style(el,n,el.dataset.independent!=='true'&&parent?{x:bounds(parent).x+(parent.borders?.[3]?.width||0),y:bounds(parent).y+(parent.borders?.[0]?.width||0)}:{x:0,y:0});content(el,n);childEls.forEach(c=>el.append(c));}
 function prepare(data){if(data._studioPrepared)return;const captured=!!(data.captureVersion||data.capturedAt||data.url);function visit(n){if(n.clip){n._sourceClip=true;n.clip=false}if(captured&&['box','group'].includes(n.type)&&n.type!=='group'&&(n.width>data.width*1.05||n.height>data.height*1.05)){const right=Math.min(data.width,n.x+n.width),bottom=Math.min(data.height,n.y+n.height);n.x=Math.max(0,n.x);n.y=Math.max(0,n.y);n.width=Math.max(.01,right-n.x);n.height=Math.max(.01,bottom-n.y)}(n.children||[]).forEach(visit)}visit(data.root);if(captured&&data.root.type==='box'){Object.assign(data.root,{name:'画板',x:0,y:0,width:data.width,height:data.height,background:null,borders:[],rasterStyle:null,clip:false})}data._studioPrepared=true;data._linkChildren=data._linkChildren!==false;}
 function exportData(data){const result=clone(data);if(data._linkChildren===false){const children=[];function flat(n){if(n.visible!==false&&painted(n))children.push({...n,children:[],clip:false});(n.children||[]).forEach(flat)}flat(result.root);result.root={type:'box',name:'画板',x:0,y:0,width:data.width,height:data.height,children};return result;}function visible(n){n.children=(n.children||[]).filter(c=>c.visible!==false).map(visible);return n}result.root=visible(result.root);return result}
 return {rgba,hex,color,clone,index,bounds,move,render,update,exportData,svg,painted,clean,prepare};
})();
