'use strict';
const $=id=>document.getElementById(id),D=CaptureDesign;
let current=null,elements=new Map(),nodes=new Map(),selected=null,busy=false,scale=1,displayScale=1,zoomMode='fit',origin={x:32,y:32},hand=false,space=false,undo=[],redo=[],collapsed=new Set(),generation=0,job=null,saveTimer,activeInline=null;
const status=text=>$('status').textContent=text;
const backgroundUI=ShijieEditorUI.background($('background-settings'),{workspace:$('preview'),get:()=>current?{color:current.background?.a>0?D.hex(current.background):null}:null,busy:()=>busy,set:value=>commit(()=>{
 current.background=value?D.color(value):null;
 // The body paint duplicates the document background in captured pages.
 if(current.root.type==='box'){current.root.background=null;if(current.root.rasterStyle){current.root.rasterStyle['background-color']='transparent';current.root.rasterStyle['background-image']='none';}}
},value?'画布背景已更新，可按 Ctrl+Z 撤销':'画布背景已设为透明，可按 Ctrl+Z 撤销')});
ShijieEditorUI.bindHistory({undo:()=>undoRedo(true),redo:()=>undoRedo(false),busy:()=>busy});
function controls(){document.body.classList.toggle('is-busy',busy);for(const id of ['file','json','psd','png','add-text','add-box','clear','clean-empty'])$(id).disabled=busy||(id!=='file'&&!current);$('undo').disabled=busy||!undo.length;$('redo').disabled=busy||!redo.length;backgroundUI?.sync();window.studio?.sync(false);window.syncWebUI?.();}
function progress(text,value){$('job-panel').hidden=false;$('job-label').textContent=text;status(text);if(value===null){$('progress').removeAttribute('value');$('job-percent').textContent='…'}else{$('progress').value=Math.max(0,Math.min(1,value));$('job-percent').textContent=Math.round($('progress').value*100)+'%'}}
function begin(text){busy=true;job=new AbortController();progress(text,0);$('cancel-job').disabled=false;controls();return job.signal}
function finish(){busy=false;job=null;$('job-panel').hidden=true;controls();props()}
$('cancel-job').onclick=()=>{job?.abort();generation++;status('正在停止处理…');$('cancel-job').disabled=true};
function scheduleSave(){clearTimeout(saveTimer);$('save-state').textContent='正在保存…';saveTimer=setTimeout(async()=>{try{await CaptureStore.set(current);$('save-state').textContent='已保存到本机'}catch{$('save-state').textContent='请导出 JSON 保存';status('本地存储空间不足，请保存工程 JSON。')}},400)}
function checkpoint(before){undo.push(before);if(undo.length>25)undo.shift();redo=[];controls();scheduleSave()}
function warnings(list){$('warnings').replaceChildren();for(const text of list){const li=document.createElement('li');li.textContent=text;$('warnings').append(li)}$('warning-count').textContent=list.length?'('+list.length+')':''}
function ancestor(n,predicate){let item=n;while(item){if(predicate(item))return true;item=nodes.get(item._sid)?.parent}return false}
function locked(n){return n&&(current?._linkChildren===false?n.locked===true:ancestor(n,x=>x.locked===true))}
function updateInfo(){if(!current)return;nodes=D.index(current);const count={text:0,vector:0,raster:0};nodes.forEach(({node:n})=>{if(n.type==='text')count.text++;else if(n.type==='image')count.raster++;else if(n.type==='svg'||n.background?.a>0||(n.borders||[]).some(b=>b.width>0))count.vector++});current.count=nodes.size;$('layer-count').textContent=nodes.size;for(const k in count)$('stat-'+k).textContent=count[k];$('source-title').textContent=current.title||'未命名页面';$('source-size').textContent=current.width+' × '+current.height+' px';$('title').textContent=current.title||'未命名页面';$('meta').textContent=current.width+' × '+current.height+' · '+nodes.size+' 层';exportSize()}
function exportSize(){if(!current)return;try{const p=ShijiePSD.exportPlan(D.exportData(current),$('export-scale').value);$('export-size').textContent=p.width+' × '+p.height+' px · '+Math.round(p.scale*100)+'%'+(p.scale<.999?'\n仅调整导出尺寸，编辑工程保留原尺寸。':'\n文字和矢量保持可编辑。');$('export-size').classList.remove('error')}catch(e){$('export-size').textContent=e.message;$('export-size').classList.add('error')}}
function tree(){const list=$('layer-tree');list.replaceChildren();if(!current)return;const query=$('layer-search').value.trim().toLowerCase(),match=new Map();function contains(n){const yes=(n.name||'').toLowerCase().includes(query)||(n.text||'').toLowerCase().includes(query);let child=false;for(const c of n.children||[])child=contains(c)||child;const result=!query||yes||child;match.set(n._sid,result);return result}contains(current.root);const fragment=document.createDocumentFragment();function visit(n,depth){if(!match.get(n._sid))return;const row=document.createElement('div');row.className='tree-row'+(n.visible===false?' dim':'');row.setAttribute('role','treeitem');row.setAttribute('aria-level',depth+1);row.setAttribute('aria-selected',String(selected===n._sid));row.tabIndex=0;row.dataset.layer=n._sid;row.style.paddingLeft=Math.min(depth*12,96)+'px';const has=!!n.children?.length;if(has)row.setAttribute('aria-expanded',String(!collapsed.has(n._sid)||!!query));const disclosure=document.createElement('button');disclosure.className='disclosure';disclosure.textContent=has?(collapsed.has(n._sid)&&!query?'▸':'▾'):'';disclosure.disabled=!has;disclosure.setAttribute('aria-label','展开或折叠 '+(n.name||'图层'));disclosure.onclick=e=>{e.stopPropagation();collapsed.has(n._sid)?collapsed.delete(n._sid):collapsed.add(n._sid);tree()};const icon=document.createElement('span');icon.className='kind';icon.textContent={text:'T',image:'▧',svg:'◇',box:has?'▣':'□',group:'▣'}[n.type];const name=document.createElement('span');name.className='layer-name';name.textContent=n.name||n.text||'图层';row.title=name.textContent;row.append(disclosure,icon,name);for(const [prop,label,on,off] of [['locked','锁定','▣','⌑'],['visible','显示','◉','○']]){const btn=document.createElement('button'),active=prop==='locked'?!!n.locked:n.visible===false;btn.className='layer-toggle'+(active?' active':'');btn.textContent=prop==='locked'?(n.locked?on:off):(n.visible===false?off:on);btn.setAttribute('aria-label',label+' '+name.textContent);btn.title=prop==='locked'?(n.locked?'解锁':'锁定'):(n.visible===false?'显示':'隐藏');btn.onclick=e=>{e.stopPropagation();if(busy)return;selected=n._sid;commit(()=>n[prop]=prop==='visible'?n.visible===false:!n.locked,prop==='visible'?'已更新显示状态':'已更新锁定状态')};row.append(btn)}row.onclick=()=>{if(!busy)select(n._sid,true)};row.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();select(n._sid,true)}};fragment.append(row);if(!collapsed.has(n._sid)||query)for(const c of [...(n.children||[])].reverse())visit(c,depth+1)}visit(current.root,0);list.append(fragment);window.studio?.sync(false)}
function select(id,fromTree=false){selected=id;const item=nodes.get(id);if(item){let p=item.parent;while(p){collapsed.delete(p._sid);p=nodes.get(p._sid)?.parent}}tree();props();selection();if(id)$('layer-tree').querySelector('[data-layer="'+id+'"]')?.scrollIntoView({block:'nearest'});if(fromTree&&item){const b=D.bounds(item.node),view=$('preview'),x=origin.x+(b.x+b.width/2)*scale,y=origin.y+(b.y+b.height/2)*scale;if(x<view.scrollLeft||x>view.scrollLeft+view.clientWidth||y<view.scrollTop||y>view.scrollTop+view.clientHeight){view.scrollLeft=Math.max(0,x-view.clientWidth/2);view.scrollTop=Math.max(0,y-view.clientHeight/2)}}}
function props(){backgroundUI.sync();const n=nodes.get(selected)?.node;$('no-selection').hidden=!!n;$('properties').hidden=!n;if(!n)return;const b=D.bounds(n),isText=n.type==='text';$('node-type').textContent={text:'文字图层',box:'框架 / 形状',group:'图层组',svg:'SVG 矢量',image:'图片'}[n.type];$('lock-hint').textContent=locked(n)?'已锁定':'';for(const [id,value] of Object.entries({'prop-name':n.name||'','prop-x':Math.round(b.x*10)/10,'prop-y':Math.round(b.y*10)/10,'prop-width':Math.round(b.width*10)/10,'prop-height':Math.round(b.height*10)/10,'prop-text':n.text||'','prop-font':n.fontFamily||'Arial','prop-size':n.fontSize||14,'prop-weight':n.fontWeight||400,'prop-fill':D.hex(isText?n.color:n.background),'prop-opacity':Math.round((n.opacity??1)*100),'prop-radius':n.radii?.[0]||0})){if(id==='prop-weight'&&!$('prop-weight').querySelector('option[value="'+value+'"]')){const o=new Option(value,value);$('prop-weight').add(o)}$(id).value=value}$('prop-visible').checked=n.visible!==false;$('prop-clip').checked=!!n.clip;$('clip-field').hidden=!n.children?.length||current._linkChildren===false;$('prop-locked').checked=!!n.locked;$('text-field').hidden=!isText;$('text-settings').hidden=!isText;$('fill-field').hidden=!['text','box'].includes(n.type);$('radius-field').hidden=n.type!=='box';for(const el of $('properties').querySelectorAll('input,textarea,select,button'))el.disabled=busy||locked(n);$('prop-locked').disabled=busy;$('prop-visible').disabled=busy;$('delete').disabled=busy||!nodes.get(selected)?.parent||locked(n);$('prop-width').disabled=$('prop-height').disabled=busy||locked(n)||n.type==='group'}
function selection(){const n=nodes.get(selected)?.node,box=$('selection');box.hidden=!n||!current||ancestor(n,x=>x.visible===false);if(!n)return;const b=D.bounds(n);Object.assign(box.style,{left:(origin.x+b.x*scale)+'px',top:(origin.y+b.y*scale)+'px',width:b.width*scale+'px',height:b.height*scale+'px'});box.classList.toggle('locked',!!locked(n));box.querySelector('.selection-label').textContent=(n.name||n.text||'图层')+' · '+Math.round(b.width)+' × '+Math.round(b.height)}
function applyZoom(anchor,preserve=false){if(!current)return;const view=$('preview'),w=view.clientWidth,h=view.clientHeight,before=displayScale,center=anchor||{x:w/2,y:h/2},point={x:(view.scrollLeft+center.x-origin.x)/before,y:(view.scrollTop+center.y-origin.y)/before};if(zoomMode==='fit')scale=Math.min(1,Math.max(.002,Math.min((w-64)/current.width,(h-64)/current.height)));else if(zoomMode==='width')scale=Math.min(2,Math.max(.002,(w-64)/current.width));else scale=Math.max(.002,Math.min(8,scale));let left=0,top=0,right=current.width,bottom=current.height;for(const {node:n} of nodes.values()){if(!D.painted(n)||n.visible===false)continue;const b=D.bounds(n);left=Math.min(left,b.x);top=Math.min(top,b.y);right=Math.max(right,b.x+b.width);bottom=Math.max(bottom,b.y+b.height)}const padX=Math.max(160,w/2),padY=Math.max(160,h/2);origin={x:padX-left*scale,y:padY-top*scale};Object.assign($('world').style,{width:Math.max(w,(right-left)*scale+padX*2)+'px',height:Math.max(h,(bottom-top)*scale+padY*2)+'px'});Object.assign($('artboard').style,{left:origin.x+'px',top:origin.y+'px',transform:'scale('+scale+')'});$('zoomlabel').textContent=(scale<.1?(scale*100).toFixed(1):Math.round(scale*100))+'%';if(zoomMode==='custom'||preserve){view.scrollLeft=origin.x+point.x*scale-center.x;view.scrollTop=origin.y+point.y*scale-center.y}else{view.scrollLeft=Math.max(0,origin.x+current.width*scale/2-w/2);view.scrollTop=Math.max(0,origin.y+current.height*scale/2-h/2)}displayScale=scale;selection();window.studio?.overlay()}
async function draw(signal,notify=()=>{},preserve=false){nodes=D.index(current);elements=await D.render(current,$('artboard'),notify,signal);$('empty').hidden=true;$('world').hidden=false;updateInfo();tree();props();applyZoom(undefined,preserve);selection();window.studio?.sync()}
async function accept(data){const previous={data:current,selected,undo,redo,collapsed:new Set(collapsed)},token=++generation,signal=job?.signal||begin('正在打开页面…');try{ShijiePSD.validateCapture(data);D.prepare(data);const cleaned=D.clean(data);current=data;selected=null;undo=[];redo=[];collapsed.clear();nodes=D.index(current);nodes.forEach(({node:n,depth})=>{if(depth>1&&n.children?.length)collapsed.add(n._sid)});zoomMode='fit';await draw(signal,p=>progress('正在建立可编辑图层',.9+p*.09));if(signal.aborted||token!==generation)throw new DOMException('已取消','AbortError');warnings(data.warnings||[]);scheduleSave();const missing=[...nodes.values()].filter(v=>v.node.type==='image'&&!v.node.image&&!v.node.imageOmitted).length;status('已打开 '+nodes.size+' 层。'+(cleaned.removed+cleaned.flattened?'已清理 '+(cleaned.removed+cleaned.flattened)+' 个空层 / 容器。':'')+(missing?missing+' 张图片使用占位，可查看导出页的还原提示。':''))}catch(e){current=previous.data;selected=previous.selected;undo=previous.undo;redo=previous.redo;collapsed=previous.collapsed;if(current)await draw();else{nodes.clear();elements.clear();$('artboard').replaceChildren();$('world').hidden=true;$('empty').hidden=false}status(e.name==='AbortError'?'已取消处理，原工程保留。':e.message)}finally{finish()}}
async function commit(change,message='已更新图层'){if(!current||busy)return;const before=D.clone(current);busy=true;controls();try{change();ShijiePSD.validateCapture(current);current._studioStep={label:message,time:Date.now()};checkpoint(before);await draw(undefined,undefined,true);status(message)}catch(e){current=before;await draw();status('修改未应用：'+e.message)}finally{busy=false;controls();props()}}
async function undoRedo(back){if(busy||!current)return;const from=back?undo:redo,to=back?redo:undo;if(!from.length)return;busy=true;controls();to.push(D.clone(current));current=from.pop();if(!D.index(current).has(selected))selected=null;await draw(undefined,undefined,true);scheduleSave();busy=false;controls();props();status(back?'已撤销':'已重做')}
$('undo').onclick=()=>undoRedo(true);$('redo').onclick=()=>undoRedo(false);
for(const id of ['name','x','y','width','height','text','font','size','weight','fill','opacity','radius','visible','locked','clip'])$('prop-'+id).onchange=async e=>{const n=nodes.get(selected)?.node;if(!n)return;if(locked(n)&&!['visible','locked'].includes(id)){props();return}await commit(()=>{const v=e.target.value,num=Number(v),b=D.bounds(n);if(['x','y','width','height','size','weight','opacity','radius'].includes(id)&&!Number.isFinite(num))throw Error('请输入有效数值');if(id==='name')n.name=v;else if(id==='x'||id==='y')D.move(n,id==='x'?num-b.x:0,id==='y'?num-b.y:0,current._linkChildren!==false);else if(id==='width'||id==='height'){n[id]=Math.max(1,Math.min(30000,num));if(n.type==='text')delete n.runs}else if(id==='text'){n.text=v;n.name=v.slice(0,40)||'文字';delete n.runs}else if(id==='font'){n.fontFamily=v;delete n.fontResolved;delete n.runs}else if(id==='size'){n.lineHeight=(n.lineHeight||n.fontSize*1.2)*Math.max(1,num)/n.fontSize;n.fontSize=Math.max(1,Math.min(1000,num));delete n.runs}else if(id==='weight'){n.fontWeight=num;delete n.runs}else if(id==='fill'){if(n.type==='text')n.color=D.color(v);else{n.background=D.color(v);if(n.rasterStyle)n.rasterStyle['background-color']=D.rgba(n.background)}}else if(id==='opacity')n.opacity=Math.max(0,Math.min(1,num/100));else if(id==='radius')n.radii=[0,0,0,0].map(()=>Math.max(0,num));else n[id]=e.target.checked})};
$('clean-empty').onclick=()=>commit(()=>{const result=D.clean(current);if(!D.index(current).has(selected))selected=null;},'空层已清理，可按 Ctrl+Z 恢复');
$('layer-search').oninput=tree;$('expand-all').onclick=()=>{collapsed.clear();tree()};$('collapse-all').onclick=()=>{nodes.forEach(({node:n})=>{if(n.children?.length&&n!==current?.root)collapsed.add(n._sid)});tree()};
function reorder(up){const item=nodes.get(selected);if(!item?.parent||locked(item.node))return;commit(()=>{const siblings=item.parent.children,i=siblings.indexOf(item.node),next=i+(up?1:-1);if(next>=0&&next<siblings.length)[siblings[i],siblings[next]]=[siblings[next],siblings[i]]},'已调整图层顺序')}
$('raise').onclick=()=>reorder(true);$('lower').onclick=()=>reorder(false);
function duplicate(){const item=nodes.get(selected);if(!item?.parent||locked(item.node))return;commit(()=>{const copy=D.clone({root:item.node}).root;function reset(n){delete n._sid;(n.children||[]).forEach(reset)}reset(copy);copy.name=(copy.name||'图层')+' 副本';D.move(copy,24,24);item.parent.children.splice(item.parent.children.indexOf(item.node)+1,0,copy);nodes=D.index(current);selected=copy._sid},'已复制图层')}
function remove(){const item=nodes.get(selected);if(!item?.parent||locked(item.node))return;commit(()=>{item.parent.children=item.parent.children.filter(n=>n!==item.node);selected=null},'已删除，可按 Ctrl+Z 恢复')}
$('duplicate').onclick=duplicate;$('delete').onclick=remove;
function add(type){if(!current)return;commit(()=>{const view=$('preview'),x=Math.max(0,Math.round((view.scrollLeft+view.clientWidth/2-origin.x)/scale-100)),y=Math.max(0,Math.round((view.scrollTop+view.clientHeight/2-origin.y)/scale-25));const n={type,name:type==='text'?'新文字':'矩形',x:Math.min(current.width-1,x),y:Math.min(current.height-1,y),width:Math.min(220,current.width),height:type==='text'?45:120,opacity:1,children:[]};if(type==='text')Object.assign(n,{text:'输入你的文字',fontFamily:'Microsoft YaHei',fontSize:28,lineHeight:40,fontWeight:400,color:{r:.1,g:.1,b:.14,a:1}});else Object.assign(n,{background:D.color('#AD9AFF'),radii:[12,12,12,12],borders:[]});current.root.children=current.root.children||[];current.root.children.push(n);nodes=D.index(current);selected=n._sid},'已添加图层')}
$('add-text').onclick=()=>add('text');$('add-box').onclick=()=>add('box');
function setHand(value){hand=value;$('hand-tool').setAttribute('aria-pressed',value);$('select-tool').setAttribute('aria-pressed',!value);$('preview').classList.toggle('hand',hand||space)}$('select-tool').onclick=()=>setHand(false);$('hand-tool').onclick=()=>setHand(true);
$('fit').onclick=()=>{zoomMode='fit';applyZoom()};$('fit-width').onclick=()=>{zoomMode='width';applyZoom()};$('actual').onclick=()=>{zoomMode='custom';scale=1;applyZoom()};$('zoomin').onclick=()=>{zoomMode='custom';scale*=1.25;applyZoom()};$('zoomout').onclick=()=>{zoomMode='custom';scale/=1.25;applyZoom()};new ResizeObserver(()=>{if(current)applyZoom()}).observe($('preview'));
$('preview').addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoomMode='custom';const old=scale,r=$('preview').getBoundingClientRect(),point={x:e.clientX-r.left,y:e.clientY-r.top};const worldPoint={x:($('preview').scrollLeft+point.x-origin.x)/old,y:($('preview').scrollTop+point.y-origin.y)/old};scale*=Math.exp(-e.deltaY*.002);applyZoom();$('preview').scrollLeft=origin.x+worldPoint.x*scale-point.x;$('preview').scrollTop=origin.y+worldPoint.y*scale-point.y},{passive:false});
let drag=null;
$('preview').addEventListener('pointerdown',e=>{if(!current||busy||e.target.closest('#inline-text')||!['0','1'].includes(String(e.button)))return;if(hand||space||e.button===1){e.preventDefault();drag={pan:true,x:e.clientX,y:e.clientY,left:$('preview').scrollLeft,top:$('preview').scrollTop};$('preview').classList.add('panning');$('preview').setPointerCapture(e.pointerId);return}const handle=e.target.dataset.handle;let id=e.target.closest('[data-node]')?.dataset.node;if(handle)id=selected;if(e.altKey&&nodes.get(id)?.parent)id=nodes.get(id).parent._sid;if(!id){select(null);return}select(id);const n=nodes.get(id)?.node;if(!n||locked(n))return;e.preventDefault();drag={id,handle,x:e.clientX,y:e.clientY,box:D.bounds(n),before:D.clone(current),moved:false};$('preview').setPointerCapture(e.pointerId)});
$('preview').addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){$('preview').scrollLeft=drag.left-(e.clientX-drag.x);$('preview').scrollTop=drag.top-(e.clientY-drag.y);return}let dx=(e.clientX-drag.x)/scale,dy=(e.clientY-drag.y)/scale;if(Math.abs(dx)+Math.abs(dy)<.5)return;const n=nodes.get(drag.id)?.node;if(!n)return;drag.moved=true;const b=D.bounds(n),old=drag.box;if(drag.handle&&n.type!=='group'){const west=drag.handle.includes('w'),north=drag.handle.includes('n');let w=Math.max(1,old.width+(west?-dx:dx)),h=Math.max(1,old.height+(north?-dy:dy));if(e.shiftKey){h=w*old.height/old.width}const x=west?old.x+old.width-w:old.x,y=north?old.y+old.height-h:old.y;D.move(n,x-b.x,y-b.y);n.width=Math.min(30000,w);n.height=Math.min(30000,h);if(n.type==='text')delete n.runs}else D.move(n,old.x+dx-b.x,old.y+dy-b.y);D.update(n,elements,nodes.get(n._sid)?.parent);selection();props()});
function endDrag(){if(!drag)return;if(drag.moved){checkpoint(drag.before);tree();status('位置与尺寸已更新')}drag=null;$('preview').classList.remove('panning')}$('preview').addEventListener('pointerup',endDrag);$('preview').addEventListener('pointercancel',endDrag);
$('preview').addEventListener('dblclick',e=>{if(busy||hand)return;const id=(e.target.closest('[data-node]')||document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]'))?.dataset.node,n=nodes.get(id)?.node;if(n?.type!=='text'||locked(n))return;select(id);activeInline={id,before:n.text};const field=$('inline-text');field.value=n.text||'';Object.assign(field.style,{left:(origin.x+n.x*scale)+'px',top:(origin.y+n.y*scale)+'px',width:Math.max(100,n.width*scale)+'px',height:Math.max(40,n.height*scale+8)+'px',fontFamily:n.fontFamily,fontSize:Math.max(10,n.fontSize*scale)+'px',lineHeight:(n.lineHeight*scale||1.2)+'px'});field.hidden=false;field.focus();field.select()});
async function finishInline(cancel=false){if(!activeInline)return;const edit=activeInline;activeInline=null;const n=nodes.get(edit.id)?.node,text=$('inline-text').value;$('inline-text').hidden=true;if(n&&!cancel&&text!==edit.before)await commit(()=>{n.text=text;n.name=text.slice(0,40)||'文字';delete n.runs},'文字已更新')}$('inline-text').onblur=()=>finishInline();$('inline-text').onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();finishInline(true)}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();finishInline()}};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable=true]'))return;if(e.code==='Space'){e.preventDefault();space=true;$('preview').classList.add('hand')}if(busy||!current)return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();undoRedo(!e.shiftKey)}else if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();undoRedo(false)}else if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate()}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove()}else if(e.key==='Escape')select(null);else if(e.key.toLowerCase()==='h')setHand(true);else if(e.key.toLowerCase()==='v')setHand(false);else if(e.key.startsWith('Arrow')){const n=nodes.get(selected)?.node;if(!n||locked(n))return;e.preventDefault();const d=e.shiftKey?10:1;commit(()=>D.move(n,e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0,e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0),'图层已移动')}});document.addEventListener('keyup',e=>{if(e.code==='Space'){space=false;$('preview').classList.toggle('hand',hand)}});window.addEventListener('blur',()=>{space=false;endDrag();$('preview').classList.toggle('hand',hand)});
function tab(name){$('design-panel').hidden=name!=='design';$('export-panel').hidden=name!=='export';$('tab-design').setAttribute('aria-pressed',name==='design');$('tab-export').setAttribute('aria-pressed',name==='export');if(name==='export')exportSize()}$('tab-design').onclick=()=>tab('design');$('tab-export').onclick=()=>tab('export');$('export-scale').onchange=exportSize;
async function download(blob,name){const url=URL.createObjectURL(blob);try{if(globalThis.chrome?.downloads)await chrome.downloads.download({url,filename:name,saveAs:true});else{const a=document.createElement('a');a.href=url;a.download=name;a.click()}}finally{setTimeout(()=>URL.revokeObjectURL(url),60000)}}
function filename(ext){return '拾界-'+String(current?.title||'网页').replace(/[\\/:*?"<>|\x00-\x1f]/g,'-').slice(0,60)+'.'+ext}
$('json').onclick=async()=>{if(!current||busy)return;try{await download(new Blob([JSON.stringify(current)],{type:'application/json'}),filename('json'));status('已保存原尺寸图层 JSON，可重新导入工作台或 Figma。')}catch(e){status(e.message)}};
async function rasterExport(format){if(!current||busy)return;const signal=begin('正在准备导出…');$('cancel-job').disabled=true;let result;try{await new Promise(r=>setTimeout(r,30));result=await ShijiePSD.renderForExport(D.exportData(current),progress,$('export-scale').value);progress(format==='psd'?'正在编码 PSD…':'正在生成 PNG…',.96);await new Promise(r=>setTimeout(r,30));const blob=format==='psd'?new Blob([ShijiePSD.encodePSD(result)],{type:'image/vnd.adobe.photoshop'}):await new Promise(r=>result.canvas.toBlob(r,'image/png'));if(!blob)throw Error('无法生成文件');await download(blob,filename(format));status(format.toUpperCase()+' 已准备下载 · '+result.psd.width+' × '+result.psd.height+' px · '+Math.round(result.exportScale*100)+'%');warnings([...(current.warnings||[]),...result.warnings])}catch(e){status('导出未完成：'+e.message)}finally{ShijiePSD.releaseRender(result);finish()}}
$('psd').onclick=()=>rasterExport('psd');$('png').onclick=()=>rasterExport('png');
async function importFile(file){if(!file||busy)return;try{if(file.size>35000000)throw Error('JSON 超过 35 MB。');begin('正在读取图层数据…');const data=JSON.parse(await file.text());await accept(data)}catch(e){status(e.message);finish()}}$('file').onchange=e=>{const f=e.target.files[0];e.target.value='';importFile(f)};$('import-empty').onclick=()=>$('file').click();for(const event of ['dragenter','dragover'])$('preview').addEventListener(event,e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();$('preview').classList.add('dragover')}});$('preview').addEventListener('dragleave',()=>$('preview').classList.remove('dragover'));$('preview').addEventListener('drop',e=>{e.preventDefault();$('preview').classList.remove('dragover');importFile(e.dataTransfer?.files[0])});
$('clear').onclick=async()=>{if(busy)return;clearTimeout(saveTimer);await CaptureStore.clear();current=null;selected=null;nodes.clear();elements.clear();undo=[];redo=[];$('artboard').replaceChildren();$('world').hidden=true;$('empty').hidden=false;$('layer-tree').replaceChildren();$('source-title').textContent='尚未导入页面';$('source-size').textContent='所有设计保存在本机';$('title').textContent='未命名页面';$('layer-count').textContent='0';$('meta').textContent='';for(const k of ['text','vector','raster'])$('stat-'+k).textContent='—';warnings([]);props();controls();status('当前页面数据已清除')};

async function captureTab(id,images){
 const signal=begin('正在读取网页结构…');let source,self,region=null;const scope=new URLSearchParams(location.search).get('scope')||'viewport';
 try{
  self=await chrome.tabs.getCurrent();source=await chrome.tabs.get(id);
  if(scope==='region'){
   progress('请在原网页拖动框选范围…',null);await chrome.tabs.update(id,{active:true});
   const selection=chrome.scripting.executeScript({target:{tabId:id},func:selectCaptureRegion});
   const abort=()=>{chrome.scripting.executeScript({target:{tabId:id},func:()=>window.__shijieSelectionCancel?.()}).catch(()=>{})};signal.addEventListener('abort',abort,{once:true});
   try{region=(await selection)[0]?.result}finally{signal.removeEventListener('abort',abort)}
   if(!region||signal.aborted)throw new DOMException('已取消','AbortError');

  }
  progress('正在读取选定范围的图层…',null);
  const result=await chrome.scripting.executeScript({target:{tabId:id},func:capturePage,args:scope==='region'?[!!images,scope,region]:[!!images,scope]});if(signal.aborted)throw new DOMException('已取消','AbortError');const data=result[0]?.result;if(!data||data.error)throw Error(data?.error||'页面未返回数据');
  D.prepare(data);D.clean(data);await embedMissingImages(data,(text,ratio)=>progress(text,.2+ratio*.65),signal);if(signal.aborted)throw new DOMException('已取消','AbortError');progress('正在打开图层工作台…',.88);await accept(data);if(scope==='region'&&self)await chrome.tabs.update(self.id,{active:true});
 }catch(e){status(e.name==='AbortError'?'已取消抓取，原工程保留。':/activeTab|all_urls/.test(e.message)?'请回到目标网页，从 Edge 工具栏点击拾界图标，再重新框选抓取。':'抓取未完成：'+e.message+(source?.url?.startsWith('file:')&&/Cannot access|permission|permissions/i.test(e.message)?'；请检查“允许访问文件 URL”。':''));finish();if(e.name!=='AbortError'&&self)await chrome.tabs.update(self.id,{active:true}).catch(()=>{});
 }finally{window.history.replaceState(null,'',location.pathname)}
}
// Do not leave capture parameters in the URL: refresh opens the saved project, not a second capture.
(async()=>{const args=new URLSearchParams(location.search);if(args.has('project'))return;if(args.has('captureTab')&&globalThis.chrome?.scripting){try{await captureTab(Number(args.get('captureTab')),args.get('images')!=='0')}finally{window.history.replaceState(null,'',location.pathname)}return}try{const data=await CaptureStore.get();if(data)await accept(data)}catch(e){status('打开工程失败：'+e.message)}controls()})();

$('demo').onclick=()=>{const url=new URL('demo.html',location.href).href;if(globalThis.chrome?.tabs)chrome.tabs.create({url});else window.open(url,'_blank')};
