/* Runs in the source page. All controls are isolated from site styles. */
async function selectCaptureRegion(){
 if(window.__shijieSelectionCancel)window.__shijieSelectionCancel();
 return new Promise(resolve=>{
  const host=document.createElement('div');host.id='shijie-region-selector';host.setAttribute('data-shijie-overlay','');host.style.cssText='all:initial!important;position:fixed!important;inset:0!important;z-index:2147483647!important;display:block!important;';
  const shadow=host.attachShadow({mode:'open'});shadow.innerHTML=`<style>:host{all:initial}*{box-sizing:border-box}.veil{position:fixed;inset:0;cursor:crosshair;touch-action:none;background:#11131b66}.box{position:fixed;border:2px solid #c4abff;box-shadow:0 0 0 99999px #10121c99;pointer-events:none}.bar{position:fixed;left:50%;top:18px;transform:translateX(-50%);display:flex;align-items:center;gap:12px;max-width:calc(100vw - 24px);padding:12px 16px;border:1px solid #625578;border-radius:12px;background:#20222ff5;box-shadow:0 8px 32px #0005;color:#eee7fc;font:13px 'Microsoft YaHei',sans-serif;cursor:default}.bar b{white-space:nowrap}.bar small{color:#a9a1bc;font-size:11px}select,button{font:12px 'Microsoft YaHei',sans-serif;border:1px solid #504760;border-radius:6px;padding:8px 10px;background:#2e2b40;color:#e3dafa;cursor:pointer}button.primary{background:#b8a0ed;color:#21182f;border-color:#b8a0ed;font-weight:600}button:disabled{opacity:.4;cursor:default}.size{position:fixed;padding:6px 10px;background:#252133;border:1px solid #857398;border-radius:5px;color:#e8d8ff;font:12px Consolas,monospace;pointer-events:none}.bottom{top:auto;bottom:18px;flex-wrap:wrap;justify-content:center}.hint{max-width:290px;line-height:1.5}@media(max-width:620px){.top small{display:none}.bar{padding:10px;gap:7px}.hint{display:none}}</style><div class="veil"><div class="box" hidden></div><div class="size" hidden></div><div class="bar top"><b>拾界 · 框选范围</b><small>拖动选择 · Enter 确认 · Esc 取消</small><button id="cancel">取消</button></div><div class="bar bottom"><span class="hint">框选网页中需要的图层</span><span>网页图层</span><button id="reset">重新框选</button><button id="confirm" class="primary" disabled>抓取选区</button></div></div>`;
  document.documentElement.append(host);const veil=shadow.querySelector('.veil'),box=shadow.querySelector('.box'),size=shadow.querySelector('.size'),confirm=shadow.querySelector('#confirm'),hint=shadow.querySelector('.hint');let start=null,rect=null,done=false;
  const clamp=(v,max)=>Math.max(0,Math.min(max,v));
  const point=e=>({x:clamp(e.clientX,innerWidth),y:clamp(e.clientY,innerHeight)});
  function reset(){rect=null;start=null;box.hidden=size.hidden=true;veil.style.background='#11131b66';confirm.disabled=true;hint.textContent='先框选当前屏幕中需要的内容'}
  function update(e){const p=point(e),x=Math.floor(Math.min(start.x,p.x)),y=Math.floor(Math.min(start.y,p.y));rect={x,y,width:Math.ceil(Math.max(start.x,p.x))-x,height:Math.ceil(Math.max(start.y,p.y))-y};box.hidden=size.hidden=false;veil.style.background='transparent';Object.assign(box.style,{left:x+'px',top:y+'px',width:rect.width+'px',height:rect.height+'px'});size.textContent=rect.width+' × '+rect.height+' px';Object.assign(size.style,{left:Math.min(x,Math.max(0,innerWidth-140))+'px',top:Math.max(0,y-32)+'px'});confirm.disabled=rect.width<8||rect.height<8;hint.textContent=confirm.disabled?'选区至少为 8 × 8 像素':'仅抓取框内内容，可直接重新拖动选框'}
  async function finish(value){if(done)return;done=true;host.remove();document.removeEventListener('keydown',keys,true);window.removeEventListener('resize',onResize);window.removeEventListener('pagehide',cancel);delete window.__shijieSelectionCancel;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));resolve(value)}
  const cancel=()=>finish(null);window.__shijieSelectionCancel=cancel;
  function submit(){if(!rect||confirm.disabled)return;finish({...rect,documentX:rect.x+scrollX,documentY:rect.y+scrollY,viewportWidth:innerWidth,viewportHeight:innerHeight,scrollX,scrollY,mode:'layers',title:document.title,url:location.href})}
  function keys(e){if(e.key==='Escape'||e.key==='Enter'){e.preventDefault();e.stopImmediatePropagation();e.key==='Escape'?cancel():submit()}}
  function onResize(){reset();hint.textContent='窗口尺寸已变化，请重新框选'}
  veil.addEventListener('wheel',e=>e.preventDefault(),{passive:false});veil.onpointerdown=e=>{if(e.button!==0||e.target.closest('.bar'))return;e.preventDefault();start=point(e);veil.setPointerCapture(e.pointerId);update(e)};veil.onpointermove=e=>{if(start)update(e)};veil.onpointerup=e=>{if(start){update(e);start=null}};veil.onpointercancel=()=>{start=null};
  shadow.querySelector('#cancel').onclick=cancel;shadow.querySelector('#reset').onclick=reset;confirm.onclick=submit;document.addEventListener('keydown',keys,true);window.addEventListener('resize',onResize);window.addEventListener('pagehide',cancel,{once:true});
 });
}
async function cropCapturedScreen(dataURL,region){
 const image=new Image();image.src=dataURL;await image.decode();const sx=image.naturalWidth/region.viewportWidth,sy=image.naturalHeight/region.viewportHeight;
 const x=Math.round(region.x*sx),y=Math.round(region.y*sy),right=Math.min(image.naturalWidth,Math.round((region.x+region.width)*sx)),bottom=Math.min(image.naturalHeight,Math.round((region.y+region.height)*sy));
 const canvas=document.createElement('canvas');canvas.width=right-x;canvas.height=bottom-y;if(canvas.width<1||canvas.height<1)throw Error('选区尺寸无效，请重新框选');canvas.getContext('2d').drawImage(image,x,y,canvas.width,canvas.height,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png');
}
