/* Shared geometry, local project library and selected-layer exports. */
window.StudioBase=(()=>{
 const clone=v=>structuredClone(v),id=()=>crypto.randomUUID();
 const bounds=items=>{if(!items.length)return null;const x=Math.min(...items.map(b=>b.x)),y=Math.min(...items.map(b=>b.y));return {x,y,width:Math.max(.01,Math.max(...items.map(b=>b.x+b.width))-x),height:Math.max(.01,Math.max(...items.map(b=>b.y+b.height))-y)}};
 const overlap=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function trimRecent(store,keepId){let kept=keepId?1:0;const r=store.index('byModeUpdated').openKeyCursor(IDBKeyRange.bound(['auto',0],['auto',Number.MAX_SAFE_INTEGER]),'prev');r.onsuccess=()=>{const c=r.result;if(!c)return;if(c.primaryKey!==keepId){if(kept<20)kept++;else store.delete(c.primaryKey)}c.continue()}}
 async function clearDraft(key,kind){const image=kind==='image',db=await new Promise((ok,no)=>{const r=indexedDB.open(image?'shijie-image-editor':'shijie-capture',1);r.onupgradeneeded=()=>r.result.createObjectStore(image?'projects':'captures');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction(image?'projects':'captures','readwrite'),s=tx.objectStore(image?'projects':'captures'),slot=image?'current':'latest',r=s.get(slot);r.onsuccess=()=>{if(r.result?._projectId===key)s.delete(slot)};tx.oncomplete=()=>{db.close();ok()};tx.onabort=tx.onerror=()=>{db.close();no(tx.error||Error('清除草稿失败'))}})}
 const library={
  async tx(mode,fn){const db=await new Promise((ok,no)=>{const r=indexedDB.open('shijie-library',2);r.onupgradeneeded=e=>{const s=e.oldVersion? r.transaction.objectStore('projects'):r.result.createObjectStore('projects',{keyPath:'id'});if(!s.indexNames.contains('byModeUpdated'))s.createIndex('byModeUpdated',['saveMode','updated']);if(e.oldVersion){const cursor=s.openCursor();cursor.onsuccess=()=>{const c=cursor.result;if(!c)return;const p=c.value;if(!p.saveMode)c.update({...p,saveMode:'saved',savedAt:p.updated||Date.now(),legacySaved:true});c.continue()}}};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return new Promise((ok,no)=>{const tx=db.transaction('projects',mode);let result;try{const r=fn(tx.objectStore('projects'));r.onsuccess=()=>result=r.result}catch(e){tx.abort();db.close();no(e);return}tx.oncomplete=()=>{db.close();ok(result)};tx.onerror=tx.onabort=()=>{db.close();no(tx.error||Error('保存未完成'))}})},
  list(){return this.tx('readonly',s=>s.getAll())},get(key){return this.tx('readonly',s=>s.get(key))},
  update(key,change){return this.tx('readwrite',s=>{const r=s.get(key);r.addEventListener('success',()=>{const entry=change(r.result);if(entry)s.put(entry)});return r})},
  put(doc,kind,options={}){const entry={id:doc._projectId,kind,title:doc.title||'未命名工程',updated:Date.now(),revision:id(),doc:clone(doc)};return this.tx('readwrite',s=>{const r=s.get(entry.id);r.addEventListener('success',()=>{const previous=r.result,saveMode=options.manual||previous&&previous.saveMode!=='auto'?'saved':'auto';const write=s.put({...entry,saveMode,savedAt:saveMode==='saved'?previous?.savedAt||Date.now():undefined,legacySaved:!!previous?.legacySaved,thumbnail:previous?.thumbnail||null,thumbnailRevision:previous?.thumbnailRevision});write.addEventListener('success',()=>trimRecent(s,saveMode==='auto'?entry.id:null))});return r})},
  async remove(key,kind){await clearDraft(key,kind);return this.tx('readwrite',s=>s.delete(key))},
  retain(key){return this.update(key,p=>p?{...p,saveMode:'saved',savedAt:p.savedAt||Date.now()}:null).then(p=>{if(!p)throw Error('这条最近记录已过期，请重新打开工程文件')})},
  cacheThumbnail(key,revision,thumbnail){return this.update(key,entry=>entry&&entry.revision===revision?{...entry,thumbnail,thumbnailRevision:revision}:null)}
 };
 function snap(box,targets,threshold){let dx=0,dy=0,bestX=threshold,bestY=threshold,gx=null,gy=null;const xs=[box.x,box.x+box.width/2,box.x+box.width],ys=[box.y,box.y+box.height/2,box.y+box.height];for(const t of targets){for(const tx of [t.x,t.x+t.width/2,t.x+t.width])for(const x of xs){const d=tx-x;if(Math.abs(d)<bestX){bestX=Math.abs(d);dx=d;gx=tx}}for(const ty of [t.y,t.y+t.height/2,t.y+t.height])for(const y of ys){const d=ty-y;if(Math.abs(d)<bestY){bestY=Math.abs(d);dy=d;gy=ty}}}return {dx,dy,gx,gy}}
 function path(p){const k=p.knots;if(!k?.length)return '';let d=`M${k[0].points[2]} ${k[0].points[3]}`;for(let i=1;i<k.length+(p.open?0:1);i++){const a=k[(i-1)%k.length].points,b=k[i%k.length].points;d+=`C${a[4]} ${a[5]} ${b[0]} ${b[1]} ${b[2]} ${b[3]}`}return d+(p.open?'':'Z')}
 function renderedSVG(render){let seq=0,defs=[];const w=render.psd.width,h=render.psd.height,rgb=c=>`rgb(${c?.r||0},${c?.g||0},${c?.b||0})`;
  function clips(body,paths){for(const p of paths){const key='clip-'+(++seq);defs.push(`<clipPath id="${key}" clipPathUnits="userSpaceOnUse"><path d="${path(p)}" clip-rule="${p.fillRule==='even-odd'?'evenodd':'nonzero'}"/></clipPath>`);body=`<g clip-path="url(#${key})">${body}</g>`}return body}
  function layer(n){let body;if(n.children)body=n.children.map(layer).join('');else if(n.text){const t=n.text,st=t.style||{};function attributes(style){const font=style.font?.name||'Arial',family=/MicrosoftYaHei/.test(font)?'Microsoft YaHei':/Arial/.test(font)?'Arial':/TimesNewRoman/.test(font)?'Times New Roman':/SegoeUIEmoji/.test(font)?'Segoe UI Emoji':/SegoeUISymbol/.test(font)?'Segoe UI Symbol':/SegoeUI/.test(font)?'Segoe UI':font;return 'font-family="'+escape(family)+'" font-size="'+(style.fontSize||14)+'" font-weight="'+(/Bold/.test(font)||style.fauxBold?700:400)+'" font-style="'+(/Italic/.test(font)||style.fauxItalic?'italic':'normal')+'" letter-spacing="'+(style.tracking||0)*(style.fontSize||14)/1000+'"';}let content=escape(t.text);if(t.styleRuns?.length){let offset=0;content=t.styleRuns.map(r=>{const text=t.text.slice(offset,offset+r.length);offset+=r.length;return '<tspan '+attributes({...st,...r.style})+'>'+escape(text)+'</tspan>'}).join('');}body='<text transform="matrix('+(t.transform||[1,0,0,1,n.left,n.top]).join(' ')+')" '+attributes(st)+' text-decoration="'+[st.underline?'underline':'',st.strikethrough?'line-through':''].filter(Boolean).join(' ')+'" fill="'+rgb(st.fillColor)+'" xml:space="preserve">'+content+'</text>';body=clips(body,n.vectorMask?.paths||[])} else if(n.vectorFill||n.vectorStroke){const paths=n.vectorMask?.paths||[],base=paths.filter(p=>p.operation!=='intersect'),inter=paths.filter(p=>p.operation==='intersect');if(n.vectorStroke?.strokeEnabled){const s=n.vectorStroke;body=`<path d="${base.map(path).join(' ')}" fill="none" stroke="${rgb(s.content?.color)}" stroke-width="${s.lineWidth?.value||1}" stroke-linecap="${s.lineCapType||'butt'}" stroke-linejoin="${s.lineJoinType||'miter'}"/>`}else{const key='mask-'+(++seq);defs.push(`<mask id="${key}" maskUnits="userSpaceOnUse" x="0" y="0" width="${w}" height="${h}"><rect width="${w}" height="${h}" fill="black"/>${base.map(p=>`<path d="${path(p)}" fill="${p.operation==='subtract'?'black':'white'}" fill-rule="${p.fillRule==='even-odd'?'evenodd':'nonzero'}"/>`).join('')}</mask>`);body=`<rect width="${w}" height="${h}" fill="${rgb(n.vectorFill?.color)}" mask="url(#${key})"/>`}body=clips(body,inter)}else if(n.canvas)body=`<image x="${n.left||0}" y="${n.top||0}" width="${n.canvas.width}" height="${n.canvas.height}" href="${n.canvas.toDataURL('image/png')}"/>`;else body='';return `<g opacity="${n.opacity??1}" data-name="${escape(n.name)}">${body}</g>`}
  const body=render.psd.children.map(layer).join('');return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs>${defs.join('')}</defs>${body}</svg>`;
 }
 return {clone,id,bounds,overlap,escape,library,snap,renderedSVG};
})();
