/* One interaction model for webpage layers and reconstructed image scenes. */
window.ShijieStudio={start(a){
 const B=StudioBase,ids=new Set(),viewport=a.viewport;let clipboard=null,gesture=null,processing=false,saveTimer,menu=null,snapEnabled=true;
 const saveProjectButton=document.getElementById('save-project'),downloadProject=saveProjectButton?.onclick;
 async function saveProject(){if(busy()||!a.get())return;clearTimeout(saveTimer);try{const doc=a.get();if(!doc._projectId)doc._projectId=B.id();await a.flush?.();await B.library.put(doc,a.kind,{manual:true});a.status('已保存到浏览器，可在「工程库 → 已保存工程」打开')}catch(e){a.status('保存失败：'+e.message)}}
 if(saveProjectButton){saveProjectButton.onclick=saveProject;saveProjectButton.title='保存到此浏览器，不参与最近 20 条自动清理'}
 document.body.classList.add('studio-enabled');
 const bar=document.createElement('div');bar.className='studio-bar';bar.innerHTML=`<span class="studio-count">未选择图层</span><button data-action="group" title="Ctrl+G">分组</button><button data-action="ungroup" title="Ctrl+Shift+G">解组</button><button data-action="align-menu">对齐 ▾</button><label class="studio-check"><input id="studio-snap" type="checkbox" checked>吸附</label><span class="studio-spacer"></span><button data-action="mask">图片修边</button><button data-action="export" class="studio-accent">导出所选 ↗</button><button data-action="history">历史</button>`;
 document.querySelector('.toolbar').before(bar);
 const projectControls=document.createElement('div');projectControls.className='project-controls';projectControls.setAttribute('role','group');projectControls.setAttribute('aria-label','工程管理');
 const libraryButton=document.createElement('button');libraryButton.dataset.action='projects';libraryButton.textContent='工程库';libraryButton.title='最近记录与已保存工程';libraryButton.onclick=()=>run('projects');projectControls.append(libraryButton);
 if(saveProjectButton)projectControls.append(saveProjectButton);
 const openProject=document.getElementById('open-project')||document.getElementById('file')?.closest('label');if(openProject)projectControls.append(openProject);
 document.querySelector('.header-actions').append(projectControls);
 const historyButton=bar.querySelector('[data-action=history]');historyButton.onclick=()=>run('history');(document.querySelector('.history-tools')||document.querySelector('.view-tools')).append(historyButton);

 const frame=document.createElement('div');frame.className='studio-selection';frame.hidden=true;frame.innerHTML='<span class="studio-selection-label"></span>'+['nw','ne','sw','se'].map(h=>`<i data-studio-handle="${h}"></i>`).join('');document.body.append(frame);
 const marquee=document.createElement('div');marquee.className='studio-marquee';marquee.hidden=true;document.body.append(marquee);
 const gx=document.createElement('div'),gy=document.createElement('div');gx.className='studio-guide vertical';gy.className='studio-guide horizontal';gx.hidden=gy.hidden=true;document.body.append(gx,gy);
 const entries=()=>a.entries(),selectedEntries=()=>{const map=entries();return [...ids].map(id=>map.get(id)).filter(Boolean)},busy=()=>processing||a.busy();
 function roots(values=[...ids]){const set=new Set(values),map=entries();return values.filter(id=>{let p=map.get(id)?.parent;while(p){if(a.independent?.())break;if(set.has(p))return false;p=map.get(p)?.parent}return map.has(id)})}
 function box(){const map=entries();return B.bounds(roots().map(id=>map.get(id).bounds))}
 function select(values,focusCanvas=false){ids.clear();for(const id of values)if(entries().has(id))ids.add(id);a.select([...ids].at(-1)||null,focusCanvas);sync(false)}
 function decorate(){a.decorate?.();const rowRoot=a.layerRoot;for(const el of rowRoot.querySelectorAll('[data-layer],[data-id],[data-studio-group]')){const id=el.dataset.layer||el.dataset.studioGroup||el.dataset.id;el.classList.toggle('studio-selected',ids.has(id));if(el.matches('[role=treeitem],[role=option]'))el.setAttribute('aria-selected',String(ids.has(id)))} }
 function overlay(){const b=box();frame.hidden=!b||!a.canSelect();if(!b)return;const r=a.rect(b);Object.assign(frame.style,{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'});frame.classList.toggle('is-locked',selectedEntries().some(e=>e.locked));frame.querySelector('span').textContent=(ids.size>1?ids.size+' 个图层 · ':'')+Math.round(b.width)+' × '+Math.round(b.height);const v=viewport.getBoundingClientRect();frame.style.clipPath=`inset(${Math.max(0,v.top-r.y-18)}px ${Math.max(0,r.x+r.width-v.right)}px ${Math.max(0,r.y+r.height-v.bottom)}px ${Math.max(0,v.left-r.x)}px)`}
 function save(){clearTimeout(saveTimer);const doc=a.get();if(!doc)return;if(!doc._projectId)doc._projectId=B.id();saveTimer=setTimeout(()=>{if(doc!==a.get())return;if(busy()){save();return}B.library.put(doc,a.kind).catch(()=>a.status('最近工程保存失败，请先下载工程文件。'))},650)}
 function sync(persist=true){const map=entries();for(const id of ids)if(!map.has(id))ids.delete(id);const primary=a.primary();if(primary&&map.has(primary)&&!ids.has(primary)){ids.clear();ids.add(primary)}bar.querySelector('.studio-count').textContent=ids.size?'已选 '+ids.size+' 层':'Shift 多选 · 空白处拖框';for(const b of bar.querySelectorAll('button'))b.disabled=busy()||(!a.get()&&!['projects'].includes(b.dataset.action))||(!ids.size&&['group','ungroup','align-menu','mask','export'].includes(b.dataset.action));libraryButton.disabled=busy();historyButton.disabled=busy()||!a.get();decorate();overlay();window.syncWebUI?.();if(persist)save()}
 async function commit(label,change){if(busy()||!a.get())return;try{processing=true;await a.commit(change,label)}catch(e){a.status(e.message)}finally{processing=false;sync()}}
 function clearGuides(){gx.hidden=gy.hidden=true}
 function guides(v){const vr=viewport.getBoundingClientRect();gx.hidden=v.gx==null;gy.hidden=v.gy==null;if(v.gx!=null){const r=a.rect({x:v.gx,y:0,width:0,height:0});Object.assign(gx.style,{left:r.x+'px',top:vr.top+'px',height:vr.height+'px'})}if(v.gy!=null){const r=a.rect({x:0,y:v.gy,width:0,height:0});Object.assign(gy.style,{top:r.y+'px',left:vr.left+'px',width:vr.width+'px'})}}
 function beginPointer(e){if(e.button!==0||busy()||!a.get()||!a.canSelect()||e.target.closest('input,textarea,[contenteditable=true]'))return;if(a.panning?.())return;const handle=e.target.dataset.studioHandle,raw=a.hit(e),id=raw?a.pick(raw,e.altKey):null,start=a.point(e);e.preventDefault();e.stopImmediatePropagation();viewport.focus({preventScroll:true});closeMenu();
  if(handle){if(!ids.size||selectedEntries().some(x=>x.locked))return}
  else if(id){if(e.shiftKey){const next=new Set(ids);next.has(id)?next.delete(id):next.add(id);select([...next]);if(!ids.has(id))return}else if(!ids.has(id))select([id]);else select([...ids].filter(v=>v!==id).concat(id));if(selectedEntries().some(x=>x.locked))return}
  else {gesture={type:'marquee',start,client:{x:e.clientX,y:e.clientY},base:e.shiftKey?[...ids]:[],moved:false};if(!e.shiftKey)select([]);return}
  const selected=roots(),map=entries(),skip=new Set(selected);for(const [key,item] of map){let p=item.parent;while(p){if(skip.has(p)){skip.add(key);break}p=map.get(p)?.parent}}
  const targets=[{x:0,y:0,width:a.get().width,height:a.get().height},...[...map.values()].filter(x=>!skip.has(x.id)&&x.visible&&x.paint&&x.bounds.width>0).map(x=>x.bounds)].slice(0,2500);
  gesture={type:handle?'resize':'move',handle,start,box:box(),before:B.clone(a.get()),ids:selected,targets,moved:false};
 }
 viewport.addEventListener('pointerdown',beginPointer,true);frame.addEventListener('pointerdown',beginPointer,true);
 document.addEventListener('pointermove',e=>{if(!gesture)return;e.preventDefault();const g=gesture,p=a.point(e);if(g.type==='marquee'){const b={x:Math.min(g.start.x,p.x),y:Math.min(g.start.y,p.y),width:Math.abs(p.x-g.start.x),height:Math.abs(p.y-g.start.y)},r=a.rect(b);g.moved=b.width+b.height>3;marquee.hidden=!g.moved;Object.assign(marquee.style,{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'});if(g.moved){const candidates=[...entries().values()].filter(x=>x.paint&&x.visible&&!x.locked&&B.overlap(b,x.bounds)).map(x=>a.pick(x.id,false));select([...new Set([...g.base,...candidates])])}return}
  let dx=p.x-g.start.x,dy=p.y-g.start.y;if(Math.abs(dx)+Math.abs(dy)<.3&&!g.moved)return;g.moved=true;let target={...g.box,x:g.box.x+dx,y:g.box.y+dy};if(g.type==='move'&&snapEnabled&&!e.altKey){const delta=B.snap(target,g.targets,6/a.scale());target.x+=delta.dx;target.y+=delta.dy;guides(delta)}else clearGuides();if(g.type==='resize'){const west=g.handle.includes('w'),north=g.handle.includes('n');let w=Math.max(1,g.box.width+(west?-dx:dx)),h=Math.max(1,g.box.height+(north?-dy:dy));if(!e.shiftKey)h=w*g.box.height/g.box.width;target={x:west?g.box.x+g.box.width-w:g.box.x,y:north?g.box.y+g.box.height-h:g.box.y,width:w,height:h};if(w>30000||h>30000)return}a.preview(g.ids,g.before,g.box,target);a.previewRender();overlay();},true);
 async function endGesture(cancel=false){const g=gesture;if(!g)return;gesture=null;marquee.hidden=true;clearGuides();if(g.type==='marquee'){if(!g.moved)select(g.base);return}if(cancel){await a.restore(g.before);sync(false)}else if(g.moved){processing=true;try{await a.finish(g.before,g.type==='move'?'移动 '+g.ids.length+' 个图层':'缩放 '+g.ids.length+' 个图层')}catch(e){await a.restore(g.before);a.status(e.message)}finally{processing=false;sync()}}}
 document.addEventListener('pointerup',()=>endGesture(),true);document.addEventListener('pointercancel',()=>endGesture(true),true);window.addEventListener('blur',()=>endGesture(true));
 a.layerRoot.addEventListener('click',e=>{if(busy()||e.target.closest('.disclosure,.layer-toggle,[data-collapse]'))return;const row=e.target.closest('[data-layer],[data-id],[data-studio-group]');if(!row)return;const id=row.dataset.layer||row.dataset.studioGroup||row.dataset.id;if(!entries().has(id))return;e.stopImmediatePropagation();if(e.shiftKey){const next=new Set(ids);next.has(id)?next.delete(id):next.add(id);select([...next],true)}else select([id],true)},true);
 function closeMenu(){menu?.remove();menu=null}
 function menuAt(x,y,items){closeMenu();menu=document.createElement('div');menu.className='studio-menu';menu.setAttribute('role','menu');for(const [key,label] of items){const b=document.createElement('button');b.textContent=label;b.setAttribute('role','menuitem');b.onclick=()=>{closeMenu();run(key)};menu.append(b)}document.body.append(menu);const r=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(innerWidth-r.width-8,x))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-r.height-8,y))+'px'}
 const contextItems=[['copy','复制图层  Ctrl+C'],['paste','粘贴图层'],['duplicate','创建副本  Ctrl+D'],['rename','重命名'],['group','分组  Ctrl+G'],['ungroup','解除分组'],['front','置于顶层'],['back','置于底层'],['lock','锁定 / 解锁'],['hide','隐藏 / 显示'],['mask','图片修边'],['export','导出所选…'],['delete','删除所选  Delete']];
 for(const host of [viewport,a.layerRoot,frame])host.addEventListener('contextmenu',e=>{if(busy())return;const row=e.target.closest('[data-layer],[data-id],[data-studio-group]'),hit=host===a.layerRoot?(row?.dataset.layer||row?.dataset.studioGroup||row?.dataset.id):a.hit(e),id=hit?a.pick(hit,e.altKey):null;if(id&&!ids.has(id))select([id],host===a.layerRoot);e.preventDefault();e.stopPropagation();menuAt(e.clientX,e.clientY,contextItems)});
 document.addEventListener('pointerdown',e=>{if(menu&&!menu.contains(e.target)&&!bar.contains(e.target))closeMenu()},true);
 function modal(title,body){const d=document.createElement('dialog');d.className='studio-dialog';d.innerHTML=`<header><div><small>SHIJIE · DESIGNED BY XT</small><h2>${B.escape(title)}</h2></div><button data-close aria-label="关闭">×</button></header><div class="studio-dialog-body">${body}</div>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d}
 function rename(){if(!ids.size)return;const d=modal('重命名图层','<label>名称<input id="studio-rename" maxlength="120"></label><footer><button class="primary" id="studio-rename-ok">保存名称</button></footer>'),input=d.querySelector('input');input.value=selectedEntries()[0]?.node.name||'';input.focus();input.select();const apply=()=>{const value=input.value.trim();if(!value)return;d.close();commit('重命名',()=>a.mutate('rename',roots(),value))};d.querySelector('#studio-rename-ok').onclick=apply;input.onkeydown=e=>{if(e.key==='Enter')apply()}}
 async function exportSelection(){if(!ids.size)return;if(a.openExport){a.openExport();return;}const b=box(),d=modal('导出所选图层',`<p class="studio-note">${ids.size} 个图层 · 按所选范围裁切 · 画布底色不包含在内</p><div class="studio-export-options"><label>格式<select id="studio-export-format"><option value="png">透明 PNG</option><option value="svg">SVG · 文字与矢量</option><option value="psd">分层 PSD</option></select></label><label>四周留白（像素）<input id="studio-export-padding" type="number" min="0" max="256" value="0"></label></div><p class="studio-note">${Math.ceil(b.width)} × ${Math.ceil(b.height)} px。图层自身的不透明背景会保留。</p><footer><span id="studio-export-status"></span><button class="primary" id="studio-export-go">导出所选</button></footer>`);d.querySelector('#studio-export-go').onclick=async e=>{e.target.disabled=true;processing=true;try{await a.export(roots(),d.querySelector('#studio-export-format').value,Math.max(0,Math.min(256,+d.querySelector('#studio-export-padding').value||0)));a.status('所选图层已导出');d.close()}catch(err){d.querySelector('#studio-export-status').textContent=err.message;e.target.disabled=false}finally{processing=false;sync(false)}}}
 async function projects(){
  clearTimeout(saveTimer);if(a.get()){if(!a.get()._projectId)a.get()._projectId=B.id();await a.flush?.();await B.library.put(a.get(),a.kind)}
  const d=modal('工程库','<div class="studio-project-tools"><input id="studio-project-search" placeholder="搜索工程名称"><button id="studio-project-copy">另存副本</button><button id="studio-project-rename">修改工程名</button><button id="studio-project-download">下载工程文件</button></div><div class="studio-project-sections"></div><p class="studio-note">保存在当前浏览器本地。最近记录最多 20 个；已保存工程不自动清理。</p>'),container=d.querySelector('.studio-project-sections'),controller=new AbortController(),cards=new Map();d.addEventListener('close',()=>controller.abort(),{once:true});
  let list=(await B.library.list()).filter(p=>p.kind==='web').sort((x,y)=>y.updated-x.updated);
  function preview(p,b){if(!b)return;const art=b.querySelector('.studio-project-art');art.replaceChildren();if(/^data:image\/(png|jpeg|webp);base64,/.test(p.thumbnail||'')){const im=document.createElement('img');im.src=p.thumbnail;im.alt=p.title+'的缩略图';im.draggable=false;art.append(im)}else{const placeholder=document.createElement('span');placeholder.className='studio-preview-placeholder';placeholder.textContent=p.previewFailed?'暂无法预览':'生成预览…';art.append(placeholder)}const size=document.createElement('small');size.textContent=p.doc.width+' × '+p.doc.height;art.append(size)}
  async function openProject(p){try{clearTimeout(saveTimer);await a.flush?.();if(a.get())await B.library.put(a.get(),a.kind);const latest=await B.library.get(p.id);if(!latest)throw Error('这条最近记录已过期，请重新打开工程文件');d.close();if(p.kind===a.kind){select([]);await a.load(B.clone(latest.doc));sync()}else throw Error('请打开网页工程')}catch(e){a.status(e.message)}}
  async function editProject(p,action){
   try{
    if(action==='delete'){
     const active=a.get()?._projectId===p.id,confirm=modal('删除工程','<p class="studio-note">确定删除「'+B.escape(p.title)+'」？'+(active?'当前画布也会关闭。':'')+' 已下载的工程文件不受影响。</p><footer><button id="project-cancel">取消</button><button id="project-delete-confirm" class="studio-danger">删除工程</button></footer>');
     confirm.classList.add('studio-small-dialog');confirm.querySelector('#project-cancel').onclick=()=>confirm.close();
     confirm.querySelector('#project-delete-confirm').onclick=async e=>{e.target.disabled=true;try{if(active)clearTimeout(saveTimer);await B.library.remove(p.id,p.kind);if(active){await a.closeProject();ids.clear();sync(false)}list=list.filter(x=>x.id!==p.id);confirm.close();show();a.status('工程已删除')}catch(err){e.target.disabled=false;a.status('删除失败：'+err.message)}};return;
    }
    if(action==='rename'){
     const edit=modal('重命名工程','<label>工程名称<input id="project-name" maxlength="120"></label><footer><button id="project-name-cancel">取消</button><button id="project-name-save" class="primary">保存名称</button></footer>');edit.classList.add('studio-small-dialog');const input=edit.querySelector('input');input.value=p.title;input.focus();input.select();edit.querySelector('#project-name-cancel').onclick=()=>edit.close();
     const apply=async()=>{const name=input.value.trim();if(!name)return;const button=edit.querySelector('#project-name-save');button.disabled=true;try{if(a.get()?._projectId===p.id){clearTimeout(saveTimer);await commit('重命名工程',()=>a.get().title=name);clearTimeout(saveTimer);await a.flush?.();await B.library.put(a.get(),a.kind)}else await B.library.update(p.id,v=>v?{...v,title:name,doc:{...v.doc,title:name}}:null);p.title=name;p.doc.title=name;edit.close();show();a.status('工程已重命名')}catch(e){button.disabled=false;a.status(e.message)}};edit.querySelector('#project-name-save').onclick=apply;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();apply()}};return;
    }
    if(action==='copy'){
     const original=a.get()?._projectId===p.id?a.get():(await B.library.get(p.id))?.doc;if(!original)throw Error('工程记录已不存在');const copy=B.clone(original);copy._projectId=B.id();copy.title=(copy.title||'未命名')+' · 副本';await B.library.put(copy,p.kind,{manual:true});list.unshift(await B.library.get(copy._projectId));show();a.status('副本已保存到浏览器');
     try{const entry=list[0],thumbnail=await ProjectThumbnail.render(entry,controller.signal);if(!controller.signal.aborted){await B.library.cacheThumbnail(entry.id,entry.revision,thumbnail);entry.thumbnail=thumbnail;entry.thumbnailRevision=entry.revision;preview(entry,cards.get(entry.id))}}catch{}return;
    }
   }catch(e){a.status(e.message)}
  }
  function show(){
   const q=d.querySelector('input').value.toLowerCase();container.replaceChildren();cards.clear();for(const key of ['copy','rename','download'])d.querySelector('#studio-project-'+key).disabled=!a.get();
   for(const saved of [true,false]){const matches=list.filter(p=>(p.saveMode!=='auto')===saved&&p.title.toLowerCase().includes(q)),section=document.createElement('section');section.className='studio-project-section';section.dataset.saveMode=saved?'saved':'auto';const heading=document.createElement('h3');heading.innerHTML=(saved?'已保存工程':'最近记录')+' <small>'+matches.length+(saved?'':' / 20')+'</small>';section.append(heading);const grid=document.createElement('div');grid.className='studio-project-grid';section.append(grid);container.append(section);
    if(!matches.length){const empty=document.createElement('p');empty.className='studio-project-empty';empty.textContent=q?'没有匹配的工程':saved?'点击「保存工程」，在这里长期保留。':'抓取或打开设计后，自动记录在这里。';grid.append(empty)}
    for(const p of matches){const card=document.createElement('article');card.className='studio-project-card';card.dataset.project=p.id;const b=document.createElement('button');b.className='studio-project-open';b.setAttribute('aria-label','打开工程 '+p.title);b.innerHTML='<span class="studio-project-art"></span><strong>'+B.escape(p.title)+'</strong><small>'+(p.kind==='web'?'网页工程':'图片工程')+' · '+new Date(p.updated).toLocaleString()+'</small>';b.onclick=()=>openProject(p);card.append(b);const footer=document.createElement('div');footer.className='studio-project-card-actions';if(saved){const badge=document.createElement('span');badge.textContent=p.legacySaved?'旧工程 · 已保留':'已保存到浏览器';footer.append(badge)}else{const button=document.createElement('button');button.className='studio-project-retain';button.textContent='保存工程';button.setAttribute('aria-label','保存工程 '+p.title);button.onclick=async()=>{button.disabled=true;try{await B.library.retain(p.id);p.saveMode='saved';show();a.status('已保存到浏览器，不参与 20 条记录清理')}catch(e){button.disabled=false;a.status(e.message)}};footer.append(button)}for(const [action,label] of [['rename','改名'],['copy','副本'],['delete','删除']]){const button=document.createElement('button');button.className='studio-project-'+action;button.textContent=label;button.setAttribute('aria-label',label+'工程 '+p.title);button.onclick=()=>editProject(p,action);footer.append(button)}card.append(footer);grid.append(card);cards.set(p.id,card);preview(p,card)}
   }
  }
  show();d.querySelector('input').oninput=show;
  (async()=>{for(const p of list){if(controller.signal.aborted)return;if(p.thumbnail&&p.thumbnailRevision===p.revision)continue;try{const thumbnail=await ProjectThumbnail.render(p,controller.signal);if(controller.signal.aborted)return;await B.library.cacheThumbnail(p.id,p.revision,thumbnail);p.thumbnail=thumbnail;p.thumbnailRevision=p.revision;preview(p,cards.get(p.id))}catch(e){if(controller.signal.aborted)return;p.previewFailed=true;preview(p,cards.get(p.id))}}})();
  for(const key of ['copy','rename','download'])d.querySelector('#studio-project-'+key).disabled=!a.get();
  d.querySelector('#studio-project-download').onclick=async()=>{try{await downloadProject?.()}catch(e){a.status(e.message)}};
  d.querySelector('#studio-project-copy').onclick=async()=>{try{const copy=B.clone(a.get());copy._projectId=B.id();copy.title=(copy.title||'未命名')+' · 副本';await B.library.put(copy,a.kind,{manual:true});d.close();await projects()}catch(e){a.status(e.message)}};
  d.querySelector('#studio-project-rename').onclick=()=>{d.close();const edit=modal('修改工程名','<label>工程名称<input maxlength="120"></label><footer><button class="primary">保存名称</button></footer>');edit.querySelector('input').value=a.get().title||'';edit.querySelector('footer button').onclick=async()=>{const name=edit.querySelector('input').value.trim();if(!name)return;edit.close();await commit('修改工程名',()=>a.get().title=name)}};
 }
 function history(){const h=a.history(),d=modal('操作历史','<p class="studio-note">本次会话的最近操作。点击一步可回到该状态；继续编辑会从这里产生新记录。</p><div class="studio-history-list"></div>'),list=d.querySelector('.studio-history-list');h.docs.forEach((doc,i)=>{const b=document.createElement('button');b.className=i===h.index?'current':'';b.innerHTML=`<span>${i===h.index?'●':'○'}</span><div>${B.escape(doc._studioStep?.label||'打开工程')}<small>${doc._studioStep?.time?new Date(doc._studioStep.time).toLocaleTimeString():'初始状态'}${i===h.index?' · 当前':''}</small></div>`;b.onclick=async()=>{if(busy())return;d.close();select([]);await a.jump(i);sync()};list.append(b)})}
 async function align(action){if(selectedEntries().some(x=>x.locked)){a.status('请先解锁所选图层');return}const chosen=roots(),map=entries();if(chosen.length<2){a.status('请先选择至少两个图层');return}const items=chosen.map(id=>({id,b:{...map.get(id).bounds}})),total=B.bounds(items.map(x=>x.b));let targets=[];if(action==='distribute-x'||action==='distribute-y'){if(items.length<3){a.status('等距排列需要至少三个图层');return}const axis=action.endsWith('x')?'x':'y',size=axis==='x'?'width':'height';items.sort((x,y)=>x.b[axis]-y.b[axis]);const first=items[0].b[axis],last=items.at(-1).b[axis]+items.at(-1).b[size],gap=(last-first-items.reduce((s,x)=>s+x.b[size],0))/(items.length-1);let pos=first;for(const item of items){targets.push({...item,to:{...item.b,[axis]:pos}});pos+=item.b[size]+gap}}else for(const item of items){const t={...item.b};if(action==='align-left')t.x=total.x;if(action==='align-center')t.x=total.x+(total.width-t.width)/2;if(action==='align-right')t.x=total.x+total.width-t.width;if(action==='align-top')t.y=total.y;if(action==='align-middle')t.y=total.y+(total.height-t.height)/2;if(action==='align-bottom')t.y=total.y+total.height-t.height;targets.push({...item,to:t})}const before=B.clone(a.get());await commit('对齐 / 等距排列',()=>targets.forEach(t=>a.preview([t.id],before,t.b,t.to)))}
 async function run(action){try{if(action==='projects')return await projects();if(action==='history')return history();if(busy()||!a.get())return;if(action==='paste'){if(!clipboard){a.status('请先复制图层');return}return await commit('粘贴图层',()=>select(a.paste(B.clone(clipboard))))}if(!ids.size)return;if(action==='copy'){clipboard=a.copy(roots());a.status('已复制 '+ids.size+' 个图层，可从右键菜单粘贴');return}if(action==='export')return await exportSelection();if(action==='align-menu'){const r=bar.querySelector('[data-action=align-menu]').getBoundingClientRect();menuAt(r.left,r.bottom+5,[['align-left','左对齐'],['align-center','水平居中'],['align-right','右对齐'],['align-top','顶端对齐'],['align-middle','垂直居中'],['align-bottom','底端对齐'],['distribute-x','水平等间距'],['distribute-y','垂直等间距']]);return}if(action.startsWith('align-')||action.startsWith('distribute-'))return await align(action);if(action==='rename')return rename();if(action==='mask'){const chosen=roots();if(chosen.length!==1){a.status('请选择一个图片图层再修边');return}const item=entries().get(chosen[0]);if(item.locked){a.status('请先解锁这个图片图层，再进行修边');return}const info=a.image(chosen[0]);if(!info){a.status('请选择已有像素的图片图层');return}const value=await StudioMask.open(info);if(value)await commit('图片修边',()=>a.setImage(chosen[0],value));return}const chosen=roots();if(!['lock','hide'].includes(action)&&selectedEntries().some(x=>x.locked)){a.status('所选包含锁定图层，请先解锁');return}await commit({group:'分组',ungroup:'解除分组',duplicate:'复制图层',delete:'删除图层',front:'置于顶层',back:'置于底层',lock:'切换锁定',hide:'切换显示',raise:'上移一层',lower:'下移一层'}[action]||action,()=>{const next=a.mutate(action,chosen);if(next)select(next)});}catch(e){a.status(e.message)}}
 bar.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action)run(action)});bar.querySelector('input').onchange=e=>snapEnabled=e.target.checked;
 for(const [key,action] of Object.entries(a.buttons||{})){const b=document.getElementById(key);b?.addEventListener('click',e=>{if(ids.size){e.preventDefault();e.stopImmediatePropagation();run(action)}},true)}
 document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||e.target.closest('textarea,select,[contenteditable=true],input:not([type=checkbox]):not([type=color]):not([type=range])'))return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();let action;if(e.key==='Escape'){closeMenu();if(gesture)endGesture(true);else select([]);return}if(busy())return;if(mod&&k==='a'){e.preventDefault();e.stopImmediatePropagation();select(a.topIds().filter(id=>{const v=entries().get(id);return v?.visible&&!v.locked}));return}if(mod&&k==='g')action=e.shiftKey?'ungroup':'group';else if(mod&&k==='c')action='copy';else if(mod&&k==='d')action='duplicate';else if(e.key==='Delete'||e.key==='Backspace')action='delete';if(action&&ids.size){e.preventDefault();e.stopImmediatePropagation();run(action)}else if(e.key.startsWith('Arrow')&&ids.size){e.preventDefault();e.stopImmediatePropagation();if(selectedEntries().some(x=>x.locked))return;const b=box(),step=e.shiftKey?10:1,target={...b,x:b.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),y:b.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)},before=B.clone(a.get());commit('键盘移动',()=>a.preview(roots(),before,b,target))}},true);
 document.addEventListener('paste',e=>{if(e.target.closest('input,textarea,[contenteditable=true]')||[...(e.clipboardData?.files||[])].some(f=>f.type.startsWith('image/'))||document.querySelector('dialog[open]'))return;if(clipboard){e.preventDefault();e.stopImmediatePropagation();run('paste')}},true);
 window.addEventListener('resize',overlay);document.addEventListener('scroll',overlay,true);new ResizeObserver(overlay).observe(viewport);
 const api={sync,select,ids,roots,run,overlay,saveProject,isBusy:busy,flush:async()=>{clearTimeout(saveTimer);if(a.get()){if(!a.get()._projectId)a.get()._projectId=B.id();await B.library.put(a.get(),a.kind)}},adapter:a};
 const requested=new URLSearchParams(location.search).get('project');if(requested)B.library.get(requested).then(async p=>{if(!p||p.kind!==a.kind)throw Error('该工程不在本机，请从工程文件导入');await a.load(p.doc);window.history.replaceState(null,'',location.pathname);sync()}).catch(e=>a.status(e.message));sync(false);return api;
}};
