/* Non-destructive local raster masks. The original pixels remain available for restore strokes. */
window.StudioMask=(()=>{
 function blur(mask,w,h,r){r=Math.round(r);if(!r)return mask;const tmp=new Float32Array(mask.length),out=new Uint8ClampedArray(mask.length),span=r*2+1;for(let y=0;y<h;y++){let sum=0;for(let i=-r;i<=r;i++)sum+=mask[y*w+Math.max(0,Math.min(w-1,i))];for(let x=0;x<w;x++){tmp[y*w+x]=sum/span;sum-=mask[y*w+Math.max(0,x-r)];sum+=mask[y*w+Math.min(w-1,x+r+1)]}}for(let x=0;x<w;x++){let sum=0;for(let i=-r;i<=r;i++)sum+=tmp[Math.max(0,Math.min(h-1,i))*w+x];for(let y=0;y<h;y++){out[y*w+x]=sum/span;sum-=tmp[Math.max(0,y-r)*w+x];sum+=tmp[Math.min(h-1,y+r+1)*w+x]}}return out}
 function removeColor(mask,pixels,w,h,x,y,tolerance,connected=true){x=Math.max(0,Math.min(w-1,Math.floor(x)));y=Math.max(0,Math.min(h-1,Math.floor(y)));const start=y*w+x,p=start*4,color=[pixels[p],pixels[p+1],pixels[p+2]],matches=i=>pixels[i*4+3]>0&&Math.max(Math.abs(pixels[i*4]-color[0]),Math.abs(pixels[i*4+1]-color[1]),Math.abs(pixels[i*4+2]-color[2]))<=tolerance;let changed=0;if(!connected){for(let i=0;i<mask.length;i++)if(matches(i)){if(mask[i])changed++;mask[i]=0}return changed}const queue=new Int32Array(mask.length),seen=new Uint8Array(mask.length);let head=0,tail=1;queue[0]=start;seen[start]=1;while(head<tail){const i=queue[head++];if(!matches(i))continue;if(mask[i])changed++;mask[i]=0;const add=j=>{if(!seen[j]){seen[j]=1;queue[tail++]=j}};if(i%w)add(i-1);if(i%w<w-1)add(i+1);if(i>=w)add(i-w);if(i<mask.length-w)add(i+w)}return changed}
 function brush(mask,w,h,a,b,r,restore){const steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/Math.max(1,r/3)));for(let s=0;s<=steps;s++){const x=a.x+(b.x-a.x)*s/steps,y=a.y+(b.y-a.y)*s/steps;for(let py=Math.max(0,Math.floor(y-r));py<=Math.min(h-1,Math.ceil(y+r));py++)for(let px=Math.max(0,Math.floor(x-r));px<=Math.min(w-1,Math.ceil(x+r));px++)if((px-x)**2+(py-y)**2<=r*r)mask[py*w+px]=restore?255:0}}
 async function open(info){
  const load=async src=>{const im=new Image();im.src=src;await im.decode();return im},original=await load(info.original||info.src),current=await load(info.src),w=original.naturalWidth,h=original.naturalHeight;
  if(w*h>12000000)throw Error('这张图片超过 1200 万像素，请先裁出需要的素材再修边');
  const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(original,0,0);const pixels=ctx.getImageData(0,0,w,h).data;ctx.clearRect(0,0,w,h);ctx.drawImage(current,0,0,w,h);const now=ctx.getImageData(0,0,w,h).data;let mask=new Uint8ClampedArray(w*h);for(let i=0;i<mask.length;i++)mask[i]=pixels[i*4+3]?Math.min(255,now[i*4+3]*255/pixels[i*4+3]):0;
  const dialog=document.createElement('dialog');dialog.className='studio-dialog mask-dialog';dialog.setAttribute('aria-label','图片修边');dialog.innerHTML=`<header><div><small>REFINE IMAGE</small><h2>图片修边 <span>原图像素保留，可随时补回</span></h2></div><button data-close aria-label="关闭修边">×</button></header><div class="mask-layout"><div class="mask-stage"></div><aside><div class="studio-section-label">工具</div><div class="mask-tools"><button data-mask="magic" aria-pressed="true">取色去背景</button><button data-mask="erase">擦除画笔</button><button data-mask="restore">保留画笔</button></div><label>取色容差 <output id="mask-tolerance-value">24</output><input id="mask-tolerance" type="range" min="0" max="120" value="24"></label><label class="studio-check"><input id="mask-connected" type="checkbox" checked> 只去除相连区域</label><label>画笔直径 <output id="mask-size-value">30 px</output><input id="mask-size" type="range" min="2" max="200" value="30"></label><label>边缘羽化 <output id="mask-feather-value">0 px</output><input id="mask-feather" type="range" min="0" max="20" value="0"></label><div class="mask-history"><button id="mask-undo" disabled>撤销</button><button id="mask-redo" disabled>重做</button></div><button id="mask-reset">恢复原图</button><p class="studio-note" id="mask-tip">在图片背景上点一下。相连区域模式可避免删除人物内部的相同颜色。</p><p class="studio-note">棋盘格表示透明。保留画笔只能恢复原图已有像素。</p></aside></div><footer><span id="mask-size-info">${w} × ${h} · 本机处理</span><div><button id="mask-cancel">取消</button><button id="mask-apply" class="primary">应用修边</button></div></footer>`;
  dialog.querySelector('.mask-stage').append(canvas);document.body.append(dialog);dialog.showModal();const $=id=>dialog.querySelector('#'+id);let mode='magic',past=[],future=[],feather=0,last=null,strokeBefore=null,resolved=false;const limit=Math.max(2,Math.min(20,Math.floor(32000000/(w*h))));
  function buttons(){$('mask-undo').disabled=!past.length;$('mask-redo').disabled=!future.length}
  function checkpoint(){past.push(mask.slice());if(past.length>limit)past.shift();future=[];buttons()}
  function output(){const m=blur(mask,w,h,feather),data=new ImageData(new Uint8ClampedArray(pixels),w,h);for(let i=0;i<m.length;i++)data.data[i*4+3]=pixels[i*4+3]*m[i]/255;return data}
  function draw(){ctx.putImageData(output(),0,0)}draw();
  function back(redo){const from=redo?future:past,to=redo?past:future;if(!from.length)return;to.push(mask.slice());mask=from.pop();draw();buttons()}
  $('mask-undo').onclick=()=>back(false);$('mask-redo').onclick=()=>back(true);$('mask-reset').onclick=()=>{checkpoint();mask.fill(255);feather=0;$('mask-feather').value='0';$('mask-feather-value').textContent='0 px';draw()};
  for(const b of dialog.querySelectorAll('[data-mask]'))b.onclick=()=>{mode=b.dataset.mask;dialog.querySelectorAll('[data-mask]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('mask-tip').textContent=mode==='magic'?'点击背景取色，拖动容差可调整下一次取色的范围。':mode==='erase'?'按住鼠标涂抹要去掉的部分。':'按住鼠标补回原图中的像素。'};
  for(const name of ['tolerance','size','feather'])$('mask-'+name).oninput=e=>{$('mask-'+name+'-value').textContent=e.target.value+(name==='tolerance'?'':' px');if(name==='feather'){feather=+e.target.value;draw()}};
  const point=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*w/r.width,y:(e.clientY-r.top)*h/r.height}};
  canvas.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const p=point(e);checkpoint();strokeBefore=past.at(-1);if(mode==='magic'){const removed=removeColor(mask,pixels,w,h,p.x,p.y,+$('mask-tolerance').value,$('mask-connected').checked);$('mask-tip').textContent='已去除 '+removed.toLocaleString()+' 个像素，可用保留画笔修补。';draw();return}last=p;brush(mask,w,h,p,p,+$('mask-size').value/2,mode==='restore');draw()};
  canvas.onpointermove=e=>{if(!last)return;const p=point(e);brush(mask,w,h,last,p,+$('mask-size').value/2,mode==='restore');last=p;draw()};canvas.onpointerup=()=>{last=null;strokeBefore=null};canvas.onpointercancel=()=>{if(strokeBefore){mask=strokeBefore;past.pop();draw();buttons()}last=null;strokeBefore=null};
  dialog.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.stopPropagation();back(e.key.toLowerCase()==='y'||e.shiftKey)}});
  return new Promise(resolve=>{function finish(result){if(resolved)return;resolved=true;dialog.close();dialog.remove();resolve(result)}dialog.oncancel=e=>{e.preventDefault();finish(null)};dialog.querySelector('[data-close]').onclick=$('mask-cancel').onclick=()=>finish(null);$('mask-apply').onclick=()=>{draw();finish({src:canvas.toDataURL('image/png'),original:info.original||info.src})}});
 }
 return {open,blur,removeColor,brush};
})();
