
/* One export destination, distinct from saving a reusable project. */
function openWebExport(selectedOnly=false){$('output-range').value=selectedOnly?'selected':'page';tab('export');syncWebUI()}
window.syncWebUI=function(){const independent=current?._linkChildren===false;for(const id of ['relation-linked','relation-independent'])$(id).disabled=!current||busy;$('relation-linked').setAttribute('aria-pressed',String(!independent));$('relation-independent').setAttribute('aria-pressed',String(independent));$('relation-hint').textContent=independent?'仅操作当前层，子级不变':'父级与子级一起变化';$('save-project').disabled=!current||busy;const format=$('output-format').value,selectedOnly=$('output-range').value==='selected';$('output-go').disabled=!current||busy||(selectedOnly&&!window.studio?.ids.size);$('output-go').textContent='导出 '+({png:'PNG',svg:'SVG',psd:'PSD',figma:'Figma 数据'}[format]);$('padding-field').hidden=!selectedOnly;$('scale-field').hidden=format==='figma';$('output-hint').textContent=format==='figma'?'生成 JSON 后，在 Figma 中运行「拾界 · Figma 导入」插件打开。':selectedOnly?'按所选范围导出；不包含画板底色。':'导出画板范围内的可见内容。';if(current){try{const data=selectedOnly&&window.studio?.ids.size?studio.adapter.selectionData(studio.roots(),+ $('output-padding').value||0):current;const p=format==='figma'?{width:data.width,height:data.height,scale:1}:ShijiePSD.exportPlan(D.exportData(data),$('export-scale').value);$('export-size').textContent=p.width+' × '+p.height+' px · '+Math.round(p.scale*100)+'%'}catch(e){$('export-size').textContent=e.message}}};
for(const [id,linked] of [['relation-linked',true],['relation-independent',false]])$(id).onclick=()=>commit(()=>{current._linkChildren=linked},linked?'父子联动':'独立操作');
for(const id of ['output-range','output-format','output-padding','export-scale'])$(id).onchange=syncWebUI;
$('save-project').onclick=async()=>{if(!current||busy)return;try{await download(new Blob([JSON.stringify(current)],{type:'application/json'}),filename('json').replace('.json','.shijie.json'));status('工程文件已下载，可从「打开工程」恢复')}catch(e){status(e.message)}};
$('output-go').onclick=async()=>{if(!current||busy)return;const type=$('output-format').value,selection=$('output-range').value==='selected',chosen=window.studio?.roots()||[];if(selection&&!chosen.length){status('请先选择图层');return}const data=D.exportData(selection?studio.adapter.selectionData(chosen,Math.max(0,Math.min(256,+$('output-padding').value||0))):current);let rendered;begin('正在导出…');$('cancel-job').disabled=true;try{let blob,ext=type==='figma'?'json':type;if(type==='figma')blob=new Blob([JSON.stringify(data)],{type:'application/json'});else{rendered=await ShijiePSD.renderForExport(data,progress,$('export-scale').value);blob=type==='psd'?new Blob([ShijiePSD.encodePSD(rendered)],{type:'image/vnd.adobe.photoshop'}):type==='svg'?new Blob([StudioBase.renderedSVG(rendered)],{type:'image/svg+xml'}):await new Promise(r=>rendered.canvas.toBlob(r,'image/png'))}if(!blob)throw Error('无法生成导出文件');await download(blob,filename(ext).replace('.'+ext,(selection?'-所选':'')+(type==='figma'?'-Figma':'')+'.'+ext));status('已导出 '+(type==='figma'?'Figma 插件数据':type.toUpperCase()));if(rendered)warnings([...(current.warnings||[]),...rendered.warnings])}catch(e){status('导出失败：'+e.message)}finally{ShijiePSD.releaseRender(rendered);finish()}};
/* Webpage model adapter. Coordinates remain absolute within each captured document. */
(()=>{
 const B=StudioBase,clone=B.clone,view=$('preview');
 const map=()=>current?D.index(current):new Map();
 function selectionData(ids,padding=0){const chosen=new Set(ids),idx=map(),box=B.bounds(ids.map(id=>D.bounds(idx.get(id).node))),x=Math.floor(box.x)-padding,y=Math.floor(box.y)-padding,w=Math.ceil(box.x+box.width)-x+padding,h=Math.ceil(box.y+box.height)-y+padding;
  function walk(n){if(chosen.has(n._sid))return current._linkChildren===false?{...clone(n),children:(n.children||[]).map(walk).filter(Boolean)}:clone(n);const children=(n.children||[]).map(walk).filter(Boolean);if(!children.length)return null;return {...clone(n),type:'box',...D.bounds(n),background:null,borders:[],rasterStyle:null,children}}
  const root=walk(current.root);D.move(root,-x,-y);return {...clone(current),_projectId:undefined,title:(current.title||'拾界')+' · 所选',width:w,height:h,background:null,scope:'region',root};
 }
 const adapter={kind:'web',viewport:view,layerRoot:$('layer-tree'),get:()=>current,primary:()=>selected,busy:()=>busy,scale:()=>scale,
  canSelect:()=>!!current,panning:()=>hand||space,point:e=>{const r=$('artboard').getBoundingClientRect();return {x:(e.clientX-r.left)/scale,y:(e.clientY-r.top)/scale}},rect:b=>{const r=$('artboard').getBoundingClientRect();return {x:r.left+b.x*scale,y:r.top+b.y*scale,width:b.width*scale,height:b.height*scale}},
  entries(){return new Map([...map()].map(([id,{node:n,parent}])=>[id,{id,node:n,parent:parent?parent._sid:null,bounds:D.bounds(n),locked:locked(n),visible:current._linkChildren===false?n.visible!==false:!ancestor(n,x=>x.visible===false),paint:n!==current.root&&D.painted(n)}]))},
  topIds:()=>current?.root.children?.map(n=>n._sid)||[],hit:e=>{const id=e.target.closest('[data-node]')?.dataset.node;return id===current?.root._sid?null:id},pick(id,alt){if(alt)return id;let item=map().get(id);while(item?.parent){if(item.parent._studioGroup)return item.parent._sid;item=map().get(item.parent._sid)}return id},
  select:(id,locate)=>select(id,locate),independent:()=>current?._linkChildren===false,status,buttons:{delete:'delete',duplicate:'duplicate',raise:'raise',lower:'lower'},
  async commit(fn,label){await commit(fn,label)},
  preview(ids,before,from,to){const src=D.index(before),dst=map(),sx=to.width/from.width,sy=to.height/from.height;
   function transform(n,b){if(b.type!=='group'){n.x=to.x+(b.x-from.x)*sx;n.y=to.y+(b.y-from.y)*sy;n.width=Math.max(.01,b.width*sx);n.height=Math.max(.01,b.height*sy)}for(const k of ['fontSize','lineHeight'])if(Number.isFinite(b[k]))n[k]=b[k]*sy;if(Number.isFinite(b.letterSpacing))n.letterSpacing=b.letterSpacing*sx;if(Number.isFinite(b.wordSpacing))n.wordSpacing=b.wordSpacing*sx;if(b.radii)n.radii=b.radii.map(v=>v*Math.min(sx,sy));if(b.borders)n.borders=b.borders.map(v=>({...v,width:v.width*Math.min(sx,sy)}));if(b.rasterStyle)n.rasterStyle=Object.fromEntries(Object.entries(b.rasterStyle).map(([k,v])=>[k,String(v).replace(/(-?[\d.]+)px/g,(_,num)=>(+num*Math.min(sx,sy))+'px')]));if(b.runs)n.runs=b.runs.map(r=>({...r,x:to.x+(r.x-from.x)*sx,y:to.y+(r.y-from.y)*sy,width:r.width*sx,height:r.height*sy}));if(current._linkChildren!==false)(n.children||[]).forEach((c,i)=>transform(c,b.children[i]));}
   for(const id of ids){const n=dst.get(id)?.node,b=src.get(id)?.node;if(n&&b)transform(n,b)}
  },previewRender(){nodes=map();for(const {node:n,parent} of nodes.values())D.update(n,elements,parent);selection()},
  async finish(before,label){ShijiePSD.validateCapture(current);current._studioStep={label,time:Date.now()};checkpoint(before);await draw(undefined,undefined,true);scheduleSave();status(label+'，可撤销')},
  async restore(doc){current=clone(doc);await draw()},
  copy(ids){return ids.map(id=>{const n=clone(map().get(id).node);if(current._linkChildren===false)n.children=[];return n})},
  paste(copies){const newIds=[];function reset(n){n._sid=B.id();(n.children||[]).forEach(reset)}for(const n of copies){reset(n);D.move(n,24,24);n.name=(n.name||'图层')+' 副本';current.root.children.push(n);newIds.push(n._sid)}return newIds},
  mutate(action,ids,value){const idx=map(),items=ids.map(id=>idx.get(id)).filter(Boolean);if(action==='duplicate')return this.paste(this.copy(ids));if(action==='delete'){for(const {node:n,parent} of items){if(!parent)throw Error('画布根图层不能删除');const at=parent.children.indexOf(n);parent.children.splice(at,1,...(current._linkChildren===false?n.children||[]:[]))}return []}
   if(action==='group'){if(items.length<2)throw Error('请选择至少两个图层');if(items.some(i=>!i.parent))throw Error('画板根层不能分组');const ancestors=n=>{const list=[];while(n){list.push(n);n=idx.get(n._sid)?.parent}return list},chains=items.map(i=>ancestors(i.parent)),parent=chains[0].find(n=>chains.every(c=>c.includes(n)));if(!parent)throw Error('没有共同父层');const original=[...parent.children],order=new Map([...idx.keys()].map((id,i)=>[id,i])),children=items.map(i=>i.node).sort((x,y)=>order.get(x._sid)-order.get(y._sid)),last=Math.max(...items.map(item=>{let n=item.node,p=item.parent;while(p!==parent){n=p;p=idx.get(p._sid).parent}return original.indexOf(n)}));for(const item of items){if(current._linkChildren!==false){let p=item.parent;while(p&&p!==parent){item.node.opacity=(item.node.opacity??1)*(p.opacity??1);if(p.visible===false)item.node.visible=false;p=idx.get(p._sid)?.parent}}item.parent.children=item.parent.children.filter(c=>c!==item.node)}const at=parent.children.filter(n=>original.indexOf(n)<=last).length,b=B.bounds(children.map(D.bounds)),group={type:'box',_sid:B.id(),name:'分组',_studioGroup:true,...b,opacity:1,background:null,borders:[],children};parent.children.splice(at,0,group);D.clean(current);return [group._sid]}
   if(action==='ungroup'){const next=[];for(const {node:n,parent} of items){if(!n._studioGroup||!parent)throw Error('请选择手动建立的分组');const at=parent.children.indexOf(n);parent.children.splice(at,1,...n.children);next.push(...n.children.map(c=>c._sid))}return next}
   if(action==='rename'){items.forEach(({node:n},i)=>n.name=value+(items.length>1?' '+(i+1):''));return ids}
   if(action==='lock'||action==='hide'){const key=action==='lock'?'locked':'visible',value=key==='locked'?!items.every(i=>i.node.locked):items.every(i=>i.node.visible===false);items.forEach(({node:n})=>n[key]=value);return ids}
   for(const parent of new Set(items.map(i=>i.parent))){if(!parent)continue;const set=new Set(ids),chosen=parent.children.filter(c=>set.has(c._sid)),other=parent.children.filter(c=>!set.has(c._sid));if(action==='front')parent.children=[...other,...chosen];if(action==='back')parent.children=[...chosen,...other];if(action==='raise'){for(let i=parent.children.length-2;i>=0;i--)if(set.has(parent.children[i]._sid)&&!set.has(parent.children[i+1]._sid))[parent.children[i],parent.children[i+1]]=[parent.children[i+1],parent.children[i]]}if(action==='lower'){for(let i=1;i<parent.children.length;i++)if(set.has(parent.children[i]._sid)&&!set.has(parent.children[i-1]._sid))[parent.children[i],parent.children[i-1]]=[parent.children[i-1],parent.children[i]]}}return ids;
  },image(id){const n=map().get(id)?.node;return n?.type==='image'&&n.image?{src:n.image,original:n._cutoutOriginal}:null},setImage(id,v){const n=map().get(id).node;n.image=v.src;n._cutoutOriginal=v.original},
  openExport(){openWebExport(true)},async export(ids,type,padding){const data=D.exportData(selectionData(ids,padding));let rendered;try{rendered=await ShijiePSD.renderForExport(data,()=>{},'auto');const blob=type==='psd'?new Blob([ShijiePSD.encodePSD(rendered)],{type:'image/vnd.adobe.photoshop'}):type==='svg'?new Blob([B.renderedSVG(rendered)],{type:'image/svg+xml'}):await new Promise(r=>rendered.canvas.toBlob(r,'image/png'));if(!blob)throw Error('无法生成文件');await download(blob,filename(type).replace('.'+type,'-所选.'+type));if(rendered.exportScale<1)status('已按 '+Math.round(rendered.exportScale*100)+'% 导出所选，原工程尺寸保持不变')}finally{ShijiePSD.releaseRender(rendered)}},selectionData,
  history(){return {docs:[...undo,current,...[...redo].reverse()].filter(Boolean),index:undo.length}},async jump(index){const h=this.history(),docs=h.docs;undo=docs.slice(0,index).map(clone);redo=docs.slice(index+1).reverse().map(clone);current=clone(docs[index]);selected=null;await draw();scheduleSave();controls();status('已回到所选历史状态')},
  async load(doc){await accept(doc)},async closeProject(){await $('clear').onclick();$('save-state').textContent='未打开工程'},async flush(){clearTimeout(saveTimer);if(current){await CaptureStore.set(current);$('save-state').textContent='已保存到本机'}}
 };
 window.studio=ShijieStudio.start(adapter);
})();
